### ISSUE TITLE
solution - multiple of two 

### ISSUE THREAD

**Issue by 95496** [SarthakKeshari/Java-Questions-and-Solutions#10]
### Enter Issue id being referred to - #9 
Your answer

### Approach/Algorithm/Pseudo Code for the selected question - 
i will use if else

### Tags for the solution(eg - Array, Basic, Stack, etc.) - 
Basic if else

**Comment by SarthakKeshari** [comment]
@95496, 
Kindly add the solution to basic codes folder.
Deadline for the solution will be 26/09/2021.
