### ISSUE TITLE
Missing Number (Bit manipulation)

### ISSUE THREAD

**Issue by divya1509** [SarthakKeshari/Java-Questions-and-Solutions#106]
### Enter your question - 
I would like to add a well-explanatory solution to the question with examples.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/missing-number/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Bit Manipulation

**Comment by SarthakKeshari** [comment]
@divya1509,
Kindly add your solution to "leetcode" folder.
Deadline - 02/10/2021

This Issue will only be counted towards ranking criteria of this repository.

Gentle advice -
Medium and hard level questions will be given preference for Hacktoberfest tag.

**Comment by SarthakKeshari** [comment]
@divya1509,
Deadline crossed
