### ISSUE TITLE
Binary Tree Maximum Path Sum

### ISSUE THREAD

**Issue by divya1509** [SarthakKeshari/Java-Questions-and-Solutions#108]
### Enter your question - 
I want to contribute a solution to Binary Tree Maximum Path Sum in Java Language.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/binary-tree-maximum-path-sum/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Trees

**Comment by SarthakKeshari** [comment]
@divya1509,
Kindly place your solution in "leetcode" folder.
Deadline - 03/10/2021
