### ISSUE TITLE
 Next Greater Element III

### ISSUE THREAD

**Issue by nik132-eng** [SarthakKeshari/Java-Questions-and-Solutions#111]
### Enter your question - 
Given a positive integer n, find the smallest integer which has exactly the same digits existing in the integer n and is greater in value than n. If no such positive integer exists, return -1.

Note that the returned integer should fit in 32-bit integer, if there is a valid answer but it does not fit in 32-bit integer, return -1

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/next-greater-element-iii/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Math ,two pointer, string

**Comment by nik132-eng** [comment]
for hacktober fest can you please assign me this question of leetcode. I will Try to solve this problem

**Comment by SarthakKeshari** [comment]
@nik132-eng,
Kindly add your solution to "leetcode" folder.
Deadline - 03/10/2021
