### ISSUE TITLE
Search a 2D Matrix

### ISSUE THREAD

**Issue by niranjana687** [SarthakKeshari/Java-Questions-and-Solutions#112]
### Enter your question - 
Write an efficient algorithm that searches for a value in an m x n matrix. This matrix has the following properties:

Integers in each row are sorted from left to right.
The first integer of each row is greater than the last integer of the previous row.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/search-a-2d-matrix/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Matrix, Binary search

@SarthakKeshari kindly assign this to me.

**Comment by SarthakKeshari** [comment]
@niranjana687,
Kindly place your solution in "leetcode" folder.
Deadline - 03/10/2021
