### ISSUE TITLE
Implement a generic stack class (OOPs)

### ISSUE THREAD

**Issue by AayushBangroo** [SarthakKeshari/Java-Questions-and-Solutions#116]
### Enter your question - 
Implement a Stack class using generics

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
OOPs, generics

**Comment by AayushBangroo** [comment]
Please assign this issue to me

**Comment by SarthakKeshari** [comment]
@AayushBangroo,
Kindly save your solution to "Data Structure/ Stacks" folder.
Deadline - 03/10/2021
