### ISSUE TITLE
Matrix Addition

### ISSUE THREAD

**Issue by Krush2311** [SarthakKeshari/Java-Questions-and-Solutions#117]
### Enter your question - 
Addition of 2 n*n matrices

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Two dimensional array

**Comment by Krush2311** [comment]
Please assign this issue to me. Also will you please add the label hacktoberfest.

**Comment by SarthakKeshari** [comment]
@Krush2311,
Kindly add you solution to "Arrays/2D Arrays" folder.
Deadline - 02/10/2021

**Comment by Rishi098** [comment]
Please assign this issue to me. and i have added a PR for 2D Array please kindly inform if you find any conflict

**Comment by Krush2311** [comment]
> @Krush2311, Kindly add you solution to "Arrays/2D Arrays" folder. Deadline - 02/10/2021

Can you please extend the deadline to 3 Oct, 21

**Comment by SarthakKeshari** [comment]
> > @Krush2311, Kindly add you solution to "Arrays/2D Arrays" folder. Deadline - 02/10/2021
> 
> Can you please extend the deadline to 3 Oct, 21

@Krush2311,
I appreciated the sense of reponsibility.

New Deadline - 03/10/2021

**Comment by Krush2311** [comment]
Thank you!
