### ISSUE TITLE
Implement Min and Max heap using generics

### ISSUE THREAD

**Issue by Monica-Chhabria** [SarthakKeshari/Java-Questions-and-Solutions#119]
### Enter your question - 
Implement Min and Max heap using generics

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Heap

**Comment by Monica-Chhabria** [comment]
Kindly assign this issue to me with hacktoberfest label

**Comment by SarthakKeshari** [comment]
@Monica-Chhabria,
Kindly add your solution to "Data Structure/Heap" folder.
Deadline - 03/10/2021
