### ISSUE TITLE
Temperature conversion

### ISSUE THREAD

**Issue by MohammedHassan07** [SarthakKeshari/Java-Questions-and-Solutions#120]
### Enter your question - 
Convert the temperature from fahrenheit to Celsius and Celsius to Fahrenheit according to user's choice. Take the temperature as input.

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic

**Comment by MohammedHassan07** [comment]
@SarthakKeshari 
Kindly arrange the issue to me

**Comment by SarthakKeshari** [comment]
@MohammedHassan07,
Kindly add your solution to "Basic Codes" folder.
Deadline - 02/10/2021

This Issue will only be counted towards ranking criteria of this repository.

Gentle advice for futher Issues -
Medium and hard level questions will be given preference for Hacktoberfest tag.
