### ISSUE TITLE
QUESTION-DSA[tower of Hanoi]

### ISSUE THREAD

**Issue by Prakhar-creator** [SarthakKeshari/Java-Questions-and-Solutions#121]
### Enter your question - 
Tower of Hanoi is a mathematical puzzle where we have three rods and n disks. The objective of the puzzle is to move the entire stack to another rod, obeying the following simple rules:
1) Only one disk can be moved at a time.
2) Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack i.e. a disk can only be moved if it is the uppermost disk on a stack.
3) No disk may be placed on top of a smaller disk.

### Enter link to the question(if question belongs to any online platform) - 
https://www.geeksforgeeks.org/java-program-for-tower-of-hanoi/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic, DSA, Easy

### Implementation Algorithm
1)Using a Method to sort the number of Disks into Source , Destination and a Temporary (Auxillary) Rod.
2)Calculating & Displaying the movement of each disks from Source to temporary to Destination Rod
3)No. of Moves of a Given N number of disks is: 2^(N)-1.
4).Main func to input Number of Disks & Calling the method.

@SarthakKeshari sir, Can I implement this code upon your Repository....??
I am Prakhar Mishra, 2nd Year (Btech, CSE) Student, Having certified in (Basic), Java Hackerrank, 5 * Hackerrank in java.

**Comment by SarthakKeshari** [comment]
@Prakhar-creator,
Go ahead, Kindly create a Games folder and add your solution in it
Deadline - 04/10/2021

Strict advice -
Be original in your code. In case of found plagarism in later review even after a successful merge may lead to ban.

**Comment by Prakhar-creator** [comment]
@SarthakKeshari Thank you sir!!!

**Comment by nobita851** [comment]
I would be happy to work on this issue.
