### ISSUE TITLE
Java Exception Handling (TRY Catch) [Hackerrank Question]

### ISSUE THREAD

**Issue by neelshah2409** [SarthakKeshari/Java-Questions-and-Solutions#123]
### Enter your question - 
Exception handling is the process of responding to the occurrence, during computation, of exceptions – anomalous or exceptional conditions requiring special processing – often changing the normal flow of program execution. (Wikipedia)

Java has built-in mechanism to handle exceptions. Using the try statement we can test a block of code for errors. The catch block contains the code that says what to do if exception occurs.

This problem will test your knowledge on try-catch block.

You will be given two integers  and  as input, you have to compute . If  and  are not  bit signed integers or if  is zero, exception will occur and you have to report it. Read sample Input/Output to know what to report in case of exceptions.

### Enter link to the question(if question belongs to any online platform) - 
https://www.hackerrank.com/challenges/java-exception-handling-try-catch/problem

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Exception Handling

**Comment by neelshah2409** [comment]
Please assign me under hacktoberfest .

**Comment by SarthakKeshari** [comment]
@neelshah2409,
Kindly add your solution to "Hackerrank" folder.
Deadline - 03/10/2021

**Comment by krish-dev-7** [comment]
can you please assign me?

**Comment by ThexXTURBOXx** [comment]
The proposed PR is not a very nice solution in my opinion.
Could you maybe assign me to this issue? There are a lot of things that would make the code more readable and safer to use.

**Comment by SarthakKeshari** [comment]
@ThexXTURBOXx,
Your suggestion is welcomed but I prefer if you could create an issue and contribute your insights to exception handling
