### ISSUE TITLE
Matrix multiplication

### ISSUE THREAD

**Issue by aadityasinha-dotcom** [SarthakKeshari/Java-Questions-and-Solutions#124]
### Enter your question - 
Multiplication of 2 n*n matrices

### Enter link to the question(if question belongs to any online platform) - 
`N/A`

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Two dimensional Array

**Comment by iamsunil25** [comment]
@SarthakKeshari assign this issue to me. i wll complete it under deadline.

**Comment by SarthakKeshari** [comment]
@iamsunil25,
Kindly add the solution to "Arrays/2D Arrays" folder
Deadline - 03/10/2021

**Comment by Rishi098** [comment]
@SarthakKeshari assign this issue to me. and please also check PR for Arrays/2D Array

**Comment by iamsunil25** [comment]
> @SarthakKeshari assign this issue to me. and please also check PR for Arrays/2D Array

@Rishi098  this issue was assigned to me first if i could not complete it within deadline then you should start your work.

**Comment by iamsunil25** [comment]
> @SarthakKeshari assign this issue to me. and please also check PR for Arrays/2D Array

i did it within deadline

**Comment by Rishi098** [comment]
@iamsunil25 ok i will wait

**Comment by iamsunil25** [comment]
> @iamsunil25 ok i will wait

thanks @Rishi098
