### ISSUE TITLE
Insertion Sort

### ISSUE THREAD

**Issue by neelshah2409** [SarthakKeshari/Java-Questions-and-Solutions#125]
### Enter your question - 
The concept behind Insertion Sort divides the range into subarrays that are sorted and unsorted. The classified portion is at the start of duration 1 and matches the first (left side) component in the array. We move through the array and expand the classified part of the array by one component during every iteration.

### Enter link to the question(if question belongs to any online platform) - 
N/A

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
array,string

**Comment by SarthakKeshari** [comment]
@neelshah2409,
Kindly add your solution to "Sorting" folder
Deadline - 03/10/2021

**Comment by RAshid602** [comment]
"Kindly assign this issue to me"

**Comment by SarthakKeshari** [comment]
@RAshid602,
You may create a new issue "Add a question" and claim it.
Till the deadline it remains with the assigned.

**Comment by SarthakKeshari** [comment]
@RAshid602,
Kindly create a new issue "Add a question" and claim it.
Till the deadline it remains with the assigned.
