### ISSUE TITLE
QuickSort Algorithm

### ISSUE THREAD

**Issue by iamsunil25** [SarthakKeshari/Java-Questions-and-Solutions#126]
### Enter your question - 
How To Implement QuickSort in Java?

## approach for solving this question
Let’s talk about the implementation of Quick sort algorithm. Quicksort algorithms take a pivot element and partitions the array around the pivot elememt. There are number of variations of Quicksot which depends on how you choose the pivot element. There of multiple ways to choose the pivot element:

Picking the first element
Pick the last element
Picking a random element
Picking median element
Next important thing to understand is, the partition() function in Quick sort algorithm. Partition function to take a pivot element, places it at right position, moves all the elements smaller than the pivot element to its left & all the elements greater to its right. Quicksort takes linear time to do so.
Then the array is divided in two parts from the pivot element (i.e. elements less than pivot & elements greater than pivot) & both the arrays are recursively sorted using Quicksort algorithm.

### Enter link to the question(if question belongs to any online platform) - 
https://www.edureka.co/blog/quicksort-in-java/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Sorting

**Comment by iamsunil25** [comment]
@SarthakKeshari i want to work on this issue. can you please assign this issue to me?

**Comment by SarthakKeshari** [comment]
@iamsunil25,
Kindly add your solution to "Sorting" folder
Deadline - 03/10/2021
