### ISSUE TITLE
Solution - Positive Negative

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/Java-Questions-and-Solutions#13]
### Enter Issue id being referred to - #12 
Your answer

### Approach/Algorithm/Pseudo Code for the selected question - I will use if else to solve the issue
Your answer

### Tags for the solution(eg - Array, Basic, Stack, etc.) - Basic, if else
Your answer

**Comment by SarthakKeshari** [comment]
@Vedansh-Keshari,
Kindly add the solution in Basic Codes folder.
Deadline 28/09/2021
