### ISSUE TITLE
Find First and Last occurence of the number in the array 

### ISSUE THREAD

**Issue by MohammedHassan07** [SarthakKeshari/Java-Questions-and-Solutions#131]
### Enter your question - 
Find First and Last occurence of the number in the array 
Time Complexity: O(logN), where N is number of comparisions

sample input: [2 4 6 9 9 11] 
Target number: 9
outpt: [3 4]

If the target number is not present print [-1 -1]

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/description/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array

**Comment by MohammedHassan07** [comment]
@SarthakKeshari 
kindly assign this issue to me

**Comment by MohammedHassan07** [comment]
@SarthakKeshari 
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@MohammedHassan07,
Kindly add your solution to "leetcode" folder.
Deadline - 04/10/2021
