### ISSUE TITLE
Strassen Algorithm

### ISSUE THREAD

**Issue by ThexXTURBOXx** [SarthakKeshari/Java-Questions-and-Solutions#133]
### Enter your question - Strassen algorithm

The Strassen algorithm provides a faster-than-standard way to multiply matrices.
It is not very useful for smaller matrices, but will perform better for large ones.

The question is as follows - Take as input an n×n matrix A and n×n matrix B.
The output shall be their multiplication calculated through the Strassen algorithm.

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Matrix, Array, Divide and conquer
 

I am suggesting this as an idea for the hacktoberfest 2021 and I would kindly ask to work on this myself as I always wanted to implement this :)

**Comment by SarthakKeshari** [comment]
@ThexXTURBOXx,
Kindly create a "Add a question" issue for the proposal suggested above.

**Comment by ThexXTURBOXx** [comment]
@SarthakKeshari I updated the issue to fit the template

**Comment by SarthakKeshari** [comment]
@ThexXTURBOXx,
Kindly add your solution to "Arrays/2D Arrays" folder.
Deadline - 04/10/2021
