### ISSUE TITLE
Intersection of two arrays

### ISSUE THREAD

**Issue by aadityasinha-dotcom** [SarthakKeshari/Java-Questions-and-Solutions#134]
### Enter your question - 
Given two arrays arr1 and arr2. We need to find the intersection of both the arrays and return the result as a list.

### Enter link to the question(if question belongs to any online platform) - 
`N\A`

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Arrays

`Example:`

![image](https://user-images.githubusercontent.com/75474786/135718541-bd85dc71-7b61-4e88-85e3-467f6c18f4ff.png)

As a part of Hacktoberfest, @SarthakKeshari please assign this issue to me

**Comment by SarthakKeshari** [comment]
@aadityasinha-dotcom,
Go ahead, Kindly add your solution to "Arrays/1D Array" folder
Deadline - 03/10/2021
