### ISSUE TITLE
Make it Divisible ( CodeChef Starters 12 challenge)

### ISSUE THREAD

**Issue by sachin4429** [SarthakKeshari/Java-Questions-and-Solutions#135]
### Enter your question - 
Given an integer N, help Chef in finding an N-digit odd positive integer X such that X is divisible by 3 but not by 9.

Note: There should not be any leading zeroes in X. In other words, 003 is not a valid 3-digit odd positive integer.

Input Format
The first line of input contains a single integer T, denoting the number of testcases. The description of the T testcases follows.
The first and only line of each test case contains a single integer N, denoting the number of digits in X.

Output Format
For each testcase, output a single line containing an N-digit odd positive integer X in decimal number system, such that X is divisible by 3 but not by 9.

Constraints
1≤T≤500
1≤N≤104
The sum of N over all test cases does not exceed 105

### Enter link to the question(if question belongs to any online platform) - 
https://www.codechef.com/START12C/problems/MAKEDIV3

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
String, Basic, Java

**Comment by sachin4429** [comment]
Can I work on this issue for Hactoberfest 2021.

**Comment by SarthakKeshari** [comment]
@sachin4429,
Kindly add your solution to "codechef" folder
Deadline - 03/10/2021

Gentle advice for futher Issues -
A bit more tough questions would be appreciated for Hacktoberfest tag.
