### ISSUE TITLE
Shuffling Parities( Codechef September Challenge 2021 Division 2 (Unrated))

### ISSUE THREAD

**Issue by manvikri22** [SarthakKeshari/Java-Questions-and-Solutions#136]
### Enter your question - 
Chef is given an array A consisting of N positive integers. Chef shuffles the array A and creates a new array B of length N, where Bi=(Ai+i)mod2, for each i(1≤i≤N).

Find the maximum possible sum of integers of the array B, if Chef shuffles the array A optimally.

### Enter link to the question(if question belongs to any online platform) - 
https://www.codechef.com/SEPT21B/problems/SHUFFLIN

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic, NumberTheory, Java

**Comment by manvikri22** [comment]
I would like to work on this issue??

**Comment by SarthakKeshari** [comment]
@manvikri22,
Kindly add your solution to "codechef" folder.
Deadline - 03/10/2021

**Comment by SarthakKeshari** [comment]
@manvikri22,
Kindly add your solution to "codechef" folder.
Deadline - 03/10/2021

Gentle advice for futher Issues -
A bit more tough questions would be appreciated for Hacktoberfest tag.
