### ISSUE TITLE
Regex Date Validation

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#137]
### Enter your question - 
Write a program to validate the date entered by the user.  Use regex to handle date format validation. 
Date format - dd/yyyy/mm

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Regex, String Handling, if

**Comment by ThexXTURBOXx** [comment]
I can handle this is in the Java language for the Hacktoberfest. Can you assign me to this issue, please? :)

**Comment by SarthakKeshari** [comment]
@ThexXTURBOXx,
Kindly add your solution to "String Handling" folder
Deadline - 04/10/2021
