### ISSUE TITLE
Merge K Sorted Lists

### ISSUE THREAD

**Issue by niranjana687** [SarthakKeshari/Java-Questions-and-Solutions#138]
### Enter your question - 
You are given an array of k linked-lists lists, each linked-list is sorted in ascending order.

Merge all the linked-lists into one sorted linked-list and return it.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/merge-k-sorted-lists/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Linked list

@SarthakKeshari please assign this to me.

**Comment by SarthakKeshari** [comment]
@niranjana687,
Kindly add your solution to "leetcode" folder.
Deadline - 02/10/2021

**Comment by 2000shivam659** [comment]
Please assign me this in **Java** language.
