### ISSUE TITLE
Find in Mountain Array

### ISSUE THREAD

**Issue by 2000shivam659** [SarthakKeshari/Java-Questions-and-Solutions#139]
### Enter your question - 
<img width="957" alt="cd" src="https://user-images.githubusercontent.com/76156804/135723383-26e9d244-babc-415d-a487-f8d71439eeaa.png">

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/find-in-mountain-array/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array

### Language

- [x] Java

**Comment by 2000shivam659** [comment]
Kindly assign me this @SarthakKeshari .

**Comment by SarthakKeshari** [comment]
@2000shivam659,
Kindly add your solution to "leetcode" folder.
Deadline - 03/10/2021

**Comment by SarthakKeshari** [comment]
@2000shivam659,
Deadline crossed
