### ISSUE TITLE
Swap 1

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#14]
### Enter your question - 
Write a program to swap two numbers (with the help of third variable).

### Enter link to the question(if question belongs to any online platform) - 
No Link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic

**Comment by dineshparekh11** [comment]
Kindly assign this issue.

**Comment by SarthakKeshari** [comment]
@dineshparekh11,
Kindly add the solution to "Basic Codes" folder.
Deadline - 29/09/2021

**Comment by dineshparekh11** [comment]
Solution of  Write a program to swap two numbers (with the help of third variable).



![Screenshot 2021-09-29 122404](https://user-images.githubusercontent.com/78658348/135234039-bcfaa708-8afc-4c13-82db-c4882e43c6d1.png)
![Screenshot 2021-09-29 122254](https://user-images.githubusercontent.com/78658348/135234062-7d62f77e-525b-47c2-9c37-c944bce8baad.png)

**Comment by SarthakKeshari** [comment]
@dineshparekh11,
Kindly created a PR. Don't share solution in comments
