### ISSUE TITLE
First Missing Positive

### ISSUE THREAD

**Issue by 2000shivam659** [SarthakKeshari/Java-Questions-and-Solutions#140]
### Enter your question - 
<img width="955" alt="sd" src="https://user-images.githubusercontent.com/76156804/135723454-035107fc-5128-4de7-87f8-d2729fb8dc6f.png">

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/first-missing-positive/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Binary Search

### Language

- [x] Java

**Comment by 2000shivam659** [comment]
Kindly assign me this @SarthakKeshari .

**Comment by SarthakKeshari** [comment]
@2000shivam659,
A participant cannot be assigned more than 2 issues at a time

**Comment by 2000shivam659** [comment]
Now Please assign me this issue.

**Comment by SarthakKeshari** [comment]
@2000shivam659,
Kindly add your solution to "leetcode" folder
Deadline - 04/10/2021
