### ISSUE TITLE
Container With Most Water

### ISSUE THREAD

**Issue by 2000shivam659** [SarthakKeshari/Java-Questions-and-Solutions#144]
### Enter your question - 
<img width="679" alt="xd" src="https://user-images.githubusercontent.com/76156804/135724045-1ed90d75-270f-4aca-bfce-41efd3f3f57f.png">

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/container-with-most-water/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array

Please assign me this issue @SarthakKeshari .

**Comment by SarthakKeshari** [comment]
@2000shivam659,
Kindly add your solution to "leetcode" folder.
Deadline - 03/10/2021
