### ISSUE TITLE
Selection Sort

### ISSUE THREAD

**Issue by iamsunil25** [SarthakKeshari/Java-Questions-and-Solutions#147]
### Enter your question - 
how to implement selection sort in java?

### Enter link to the question(if question belongs to any online platform) - 
NA

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Sorting

**Comment by SarthakKeshari** [comment]
@iamsunil25,
Go ahead, Kindly add your solution to "Sorting" folder
Deadline - 04/10/2021
