### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by iamsunil25** [SarthakKeshari/Java-Questions-and-Solutions#148]
### Enter your question - 
How to implement bubble sort in java?

### Enter link to the question(if question belongs to any online platform) - 
NA

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Sorting

**Comment by SarthakKeshari** [comment]
@iamsunil25,
At a time more than 2 issues cannot be assigned.

**Comment by iamsunil25** [comment]
no actually here you can assign this issue to another person

**Comment by iamsunil25** [comment]
don't assign me this issue but for generating this issue you can give me point. isn't it?

**Comment by SarthakKeshari** [comment]
@iamsunil25,
Points are for PRs only.
You may complete the previous questions and claim this again

**Comment by iamsunil25** [comment]
> @iamsunil25, Points are for PRs only. You may complete the previous questions and claim this again

okay i got you

**Comment by iamsunil25** [comment]
@SarthakKeshari

**Comment by Aditya01237** [comment]
can i solve this issue  in java

**Comment by Aditya01237** [comment]
plz assign any question

**Comment by SarthakKeshari** [comment]
@Aditya01237,
Go ahead, Kindly add your solution to "Sorting" folder
Deadline - 03/10/2021

**Comment by tandrimasingha** [comment]
Name: Tandrima Singha
Domain: Java
Hello @SarthakKeshari Sir please assign this task to me

**Comment by SarthakKeshari** [comment]
@tandrimasingha,
Since the process followed is First come First Serve. So for now I would suggest you to create a new issue and claim it.
Kindly refer CONTRIBUTING.md for further details

**Comment by SarthakKeshari** [comment]
@Aditya01237,
Deadline crossed

**Comment by Lakshay-Pruthi** [comment]
Hey @SarthakKeshari ,Can you assign it to me now.

**Comment by SarthakKeshari** [comment]
@Lakshay-Pruthi,
Go ahead, Kindly add your solution to "Sorting" folder
Deadline - 05/10/2021
