### ISSUE TITLE
Counting Sort

### ISSUE THREAD

**Issue by iamsunil25** [SarthakKeshari/Java-Questions-and-Solutions#149]
### Enter your question - 
How to implement counting sort in java?

### Enter link to the question(if question belongs to any online platform) - 
NA

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Sorting

**Comment by iamsunil25** [comment]
@SarthakKeshari assign

**Comment by Debdeep1** [comment]
Please assign this task to me. I am a Java programmer.

**Comment by SarthakKeshari** [comment]
@Debdeep1,
Go ahead, Kindly add your solution to "Sorting" folder
Deadline - 03/10/2021

**Comment by Gourav-s12** [comment]
can i get this issue?

**Comment by SarthakKeshari** [comment]
@Gourav-s12,
Go ahead, Kindly add your solution to "Sorting" folder
Deadline - 06/10/2021

**Comment by JohnLennox** [comment]
Hi, please may I have this issue?
