### ISSUE TITLE
Swap 2

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#15]
### Enter your question - 
Write a program to swap two numbers (WITHOUT the help of third variable).

### Enter link to the question(if question belongs to any online platform) - 
No Link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic

**Comment by Ln11211** [comment]
hello, I have an idea using arithmetic operators "+" and "-", it works fine in theory, can I try this out please ?

**Comment by SarthakKeshari** [comment]
@Ln11211,
Kindly place your solution in "Basic Codes" folder.
Deadline - 30/09/2021
