### ISSUE TITLE
[Count 1's bit]

### ISSUE THREAD

**Issue by satyam878** [SarthakKeshari/Java-Questions-and-Solutions#152]
### Enter your question - 
Write a program that takes an unsigned integer and returns the number of '1' bits it has

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/number-of-1-bits/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
bit-manipulation

**Comment by satyam878** [comment]
Kindly approve @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@satyam878,
Kindly work on this completely. #59

**Comment by satyam878** [comment]
I have completed all my remaining works please look into it

**Comment by SarthakKeshari** [comment]
@satyam878,
Code has **not** been commented.
Checklist has been filled in the wrong manner.

**Comment by satyam878** [comment]
I have commented in code and please help me to fill the checklist as i am
getting it, like in what way you are expecting me to fill it.

**Comment by SarthakKeshari** [comment]
@satyam878,
Checklist is filled - 

[] Hello ➡  [x] Hello ✔

**Comment by satyam878** [comment]
Kindly assign me this task i have completed with my previous PR's.

**Comment by SarthakKeshari** [comment]
@satyam878,
Kindly add your solution to "leetcode" folder.
Deadline - 04/10/2021.

Gentle advice for futher Issues -
Medium and hard level questions will be given preference for Hacktoberfest tag.
