### ISSUE TITLE
Median of two sorted arrays

### ISSUE THREAD

**Issue by umang345** [SarthakKeshari/Java-Questions-and-Solutions#154]
### Enter your question - 
Given two sorted arrays, return the median of the two sorted arrays

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/median-of-two-sorted-arrays/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Binary Search

**Comment by umang345** [comment]
Can I work on this?

**Comment by SarthakKeshari** [comment]
@umang345,
Kindly add your solution to "leetcode" folder.
Deadline - 04/10/2021
