### ISSUE TITLE
1828. Queries on Number of Points Inside a Circle

### ISSUE THREAD

**Issue by sachin4429** [SarthakKeshari/Java-Questions-and-Solutions#155]
### Enter your question - 
You are given an array points where points[i] = [xi, yi] is the coordinates of the ith point on a 2D plane. Multiple points can have the same coordinates.

You are also given an array queries where queries[j] = [xj, yj, rj] describes a circle centered at (xj, yj) with a radius of rj.

For each query queries[j], compute the number of points inside the jth circle. Points on the border of the circle are considered inside.

Return an array answer, where answer[j] is the answer to the jth query.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/queries-on-number-of-points-inside-a-circle/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Maths, basic, Array, Geometry

**Comment by sachin4429** [comment]
Can I work on this issue for Hactoberfest 2021

**Comment by SarthakKeshari** [comment]
@sachin4429,
Kindly add your solution to "leetcode" folder.
Deadline - 03/10/2021
