### ISSUE TITLE
Fascinating Number or not

### ISSUE THREAD

**Issue by dineshparekh11** [SarthakKeshari/Java-Questions-and-Solutions#159]
### Enter your question - 
Find given number is Fascinating Number or not

### Enter link to the question(if question belongs to any online platform) - 
https://www.javatpoint.com/fascinating-number-in-java

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Basic,
![fascno1](https://user-images.githubusercontent.com/78658348/135729640-d3929f3e-318a-4edf-9132-1a7157397971.png)

**Comment by dineshparekh11** [comment]
Kindly assign #159 issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@dineshparekh11,
Kindly add your solution to "Number Theory" folder.
Deadline - 04/10/2021
