### ISSUE TITLE
Factorial 1

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#16]
### Enter your question - 
Write a program to find factorial of a number entered by the user. (Using loop)

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic, loops

**Comment by vish-han** [comment]
Please assign me ...

**Comment by SarthakKeshari** [comment]
@vish-han,
Kindly add your solution to "Basic Codes" folder
Deadline 29/09/2021

**Comment by vish-han** [comment]
ok @SarthakKeshari 😀

**Comment by vish-han** [comment]
plz check and review the pull request I have done this task...

**Comment by SarthakKeshari** [comment]
@vish-han, I have reviewed your pull request

**Comment by MohammedHassan07** [comment]
@SarthakKeshari 
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@vish-han,
Pull hasn't been generated. Kindly generate again and check in Pull request section.

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
following are my accounts:
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
