### ISSUE TITLE
Armstrong Number

### ISSUE THREAD

**Issue by vish-han** [SarthakKeshari/Java-Questions-and-Solutions#161]
### Enter your question - 
You have a given a number , you have to find out is that number a Armstrong number or not. 

### Enter link to the question(if question belongs to any online platform) - 
https://www.google.com/amp/s/www.geeksforgeeks.org/program-for-armstrong-numbers/amp/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
JAVA , Armstrong number

**Comment by vish-han** [comment]
Please assign this issue to me I can handle it easily..

**Comment by SarthakKeshari** [comment]
@vish-han,
Kindly add you solution to "Number Theory" folder.
Deadline - 03/10/2021

**Comment by vish-han** [comment]
Thanks sir for assigning me😄

**Comment by HatimTai1** [comment]
please assign this issue to me.

**Comment by vish-han** [comment]
@HatimTai1 bro first come first serve...😃

**Comment by SarthakKeshari** [comment]
@HatimTai1,
Kindly create a new issue "Add a question" and claim it.
Till the deadline issue remains with the assigned person.
