### ISSUE TITLE
Searching and Sorting

### ISSUE THREAD

**Issue by RAshid602** [SarthakKeshari/Java-Questions-and-Solutions#164]
### Enter link to the question(if question belongs to any online platform) - 
NA

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Java, Searching and Sorting

**Comment by RAshid602** [comment]
"Kindly assign this issue to me"
I can solve this is easy way so that student can easily understand.

**Comment by SarthakKeshari** [comment]
@RAshid602,
This issue has already been addressed
