### ISSUE TITLE
Factorial 2

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#17]
### Enter your question - 
Write a program to find factorial of a number entered by the user. (Using recursion)

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
recursion, if

**Comment by SarveshLimaye** [comment]
@SarthakKeshari would like to work on this issue. Pls, assign me this issue.

**Comment by SarthakKeshari** [comment]
@SarveshLimaye,
Kindly add your solution to "Basic Codes" folder.
Deadline - 30/09/2021
