### ISSUE TITLE
NQueens

### ISSUE THREAD

**Issue by Venkatesh-24** [SarthakKeshari/Java-Questions-and-Solutions#172]
### Enter your question 
The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.
Given an integer n, we must return all distinct solutions to the n-queens puzzle. 

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/n-queens/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Backtracking

**Comment by Venkatesh-24** [comment]
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@Venkatesh-24,
Kindly add your solution to "leetcode" folder.
Deadline - 04/10/2021
