### ISSUE TITLE
SemiSort 2

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#176]
### Enter your question - 
Write a program to sort the array according to given condition.
Sort all the elements at even index in ascending order and all the elements at odd index in descending order.
#### Reminder - Array index starts from 0.

Example - 
Input:
5
4 4 2 5 2

Output:
2 5 2 4 4

Explaination - 
Array: 4 4 2 5 2
Index: 0 1 2 3 4

Now sorting even indexes in ascending order and odd indexes in descending order
Even and odd indexes sorted Array - 
2 5 2 4 4

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Sorting, loops, logic

**Comment by Vedansh-Keshari** [comment]
@SarthakKeshari 
Please kindly assign me this issue
I really wish to work upon this

**Comment by SarthakKeshari** [comment]
@Vedansh-Keshari,
Kindly add your solution to "Sorting" folder
Deadline - 04/10/2021
