### ISSUE TITLE
Replace pi  with value of pi

### ISSUE THREAD

**Issue by RAshid602** [SarthakKeshari/Java-Questions-and-Solutions#178]
### Enter your question - 
You will be given a string and if you find "pi" you will have to replace with "3.14"
and print. (Recursively)

### Enter link to the question(if question belongs to any online platform) -
https://www.geeksforgeeks.org/recursive-program-to-replace-all-occurrences-of-pi-with-3-14-in-a-given-string/

### Tags for the question
String, recursion

**Comment by RAshid602** [comment]
Assign this to me, I will solve this in a way which help student to  understand easily.

**Comment by SarthakKeshari** [comment]
@RAshid602,
Kindly mention the link to the question since its from an online platform

**Comment by RAshid602** [comment]
i think its from GFG but i was unable to find it.
can i still do it?

**Comment by SarthakKeshari** [comment]
Definitely

**Comment by SarthakKeshari** [comment]
@RAshid602,
Go ahead, Kindly add your solution to "GeeksForGeeks" folder.
Deadline - 04/10/2021

Gentle advice for futher Issues -
Medium and hard level questions will be given preference for Hacktoberfest tag.
