### ISSUE TITLE
Count Inversion

### ISSUE THREAD

**Issue by RAshid602** [SarthakKeshari/Java-Questions-and-Solutions#179]
### Enter your question - 
Given an array of integers. Find the Inversion Count in the array. 

### Enter link to the question(if question belongs to any online platform) - 
https://practice.geeksforgeeks.org/problems/inversion-of-array-1587115620/1

### Tags for the question
Array, sorting

**Comment by RAshid602** [comment]
Kindly Assign this to me,

**Comment by SarthakKeshari** [comment]
@RAshid602,
Kindly save your solution in "GeeksForGeeks" folder.
Deadline - 04/10/2021
