### ISSUE TITLE
Find all missing number in array

### ISSUE THREAD

**Issue by MohammedHassan07** [SarthakKeshari/Java-Questions-and-Solutions#182]
### Enter your question - 
Find all missing number in array
you have given a array [1, n], you have to find the all missing number in the array
time complexity: O(n)
Sample input: [1 3 2 5 8 7 2 5]
output: [4 6]

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/description/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Searching

**Comment by MohammedHassan07** [comment]
@SarthakKeshari 
kindly assign this issue to me

**Comment by MohammedHassan07** [comment]
@SarthakKeshari 
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@MohammedHassan07,
Kindly add your solution in "Arrays/1D Arrays" folder
Deadline - 04/10/2021

Gentle advice for futher Issues -
Medium and hard level questions will be given preference for Hacktoberfest tag.
