### ISSUE TITLE
442. Find All Duplicates in an Array

### ISSUE THREAD

**Issue by Kaustubh-git** [SarthakKeshari/Java-Questions-and-Solutions#183]
### Enter your question - 
Given an integer array nums of length n where all the integers of nums are in the range [1, n] and each integer appears once or twice, return an array of all the integers that appears twice.

You must write an algorithm that runs in O(n) time and uses only constant extra space.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/find-all-duplicates-in-an-array/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Cyclic sort, Arraylist

**Comment by Kaustubh-git** [comment]
kindly assign me this issue @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@Kaustubh-git,
Kindly add your solution to "leetcode" folder.
Deadline - 04/10/2021
