### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by Kaustubh-git** [SarthakKeshari/Java-Questions-and-Solutions#185]
### Enter your question - 
Write the program to perform binary search

### Enter link to the question(if question belongs to any online platform) - 
no link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
searching, loop

**Comment by Kaustubh-git** [comment]
kindly assign me this issue @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@Kaustubh-git,
Kindly add your solution to "Searching" folder
Deadline - 04/10/2021

**Comment by tandrimasingha** [comment]
Name: Tandrima Singha
Domain: Java
Hello @SarthakKeshari Sir Please assign this task to me . I am very good at java

**Comment by SarthakKeshari** [comment]
@tandrimasingha,
Since the process followed is First come First Serve. So for now I would suggest you to create a new issue and claim it.
Kindly refer CONTRIBUTING.md for further details
