### ISSUE TITLE
Next permutation

### ISSUE THREAD

**Issue by RAshid602** [SarthakKeshari/Java-Questions-and-Solutions#187]
### Enter your question - 
Implement next permutation, which rearranges numbers into the lexicographically next greater permutation of numbers.
If such an arrangement is not possible, it must rearrange it as the lowest possible order (i.e., sorted in ascending order).

### Enter link to the question(if question belongs to any online platform) - 
I had this question in my university exam.

**Comment by RAshid602** [comment]
Can you assign this to me, so that i can solve it.

**Comment by SarthakKeshari** [comment]
@RAshid602,
Kindly add your solution to "Number Theory" folder.
Deadline - 04/10/2021
