### ISSUE TITLE
Insertion Sort

### ISSUE THREAD

**Issue by tandrimasingha** [SarthakKeshari/Java-Questions-and-Solutions#188]
### Enter your question - 
Write a program on Insertion Sort

### Enter link to the question(if question belongs to any online platform) - 
Your answer

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Sorting Algorithm

**Comment by tandrimasingha** [comment]
Hello @SarthakKeshari Sir please assign me this issue

**Comment by SarthakKeshari** [comment]
@tandrimasingha,
Kindly save your solution to "Sorting" folder.
Deadline - 04/10/2021
