### ISSUE TITLE
Queue 

### ISSUE THREAD

**Issue by tandrimasingha** [SarthakKeshari/Java-Questions-and-Solutions#189]
### Enter your question - 
write a program on the Implementation of the queue

### Enter link to the question(if question belongs to any online platform) - 
no link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Queue Data Structure

**Comment by tandrimasingha** [comment]
Hello @SarthakKeshari Sir please assign this issue to me

**Comment by SarthakKeshari** [comment]
@tandrimasingha,
Kindly add title

**Comment by tandrimasingha** [comment]
@SarthakKeshari Sir . I added the title . Please assign this to me

**Comment by SarthakKeshari** [comment]
@tandrimasingha,
Kindly add your solution to "Data Structure/Queue/Basic Queue" folder
Deadline - 04/10/2021

**Comment by Gourav-s12** [comment]
can i get the issue?
i will do it by today

**Comment by SarthakKeshari** [comment]
@Gourav-s12,
Kindly add your solution to "Data Structure/Queue/Basic Queue" folder
Deadline - 06/10/2021

**Comment by Gourav-s12** [comment]
I have made a only a basic queue .Because you said "Kindly add your solution to "Data Structure/Queue/Basic Queue" folder". please do correct me if i am wrong. And thank you.

> @Gourav-s12, Kindly add your solution to "Data Structure/Queue/Basic Queue" folder Deadline - 06/10/2021
