### ISSUE TITLE
Prime number between ranges

### ISSUE THREAD

**Issue by satyam878** [SarthakKeshari/Java-Questions-and-Solutions#19]
### Enter your question - 
Write a program that displays the primes number between the given ranges
Input constraint 
Stating , ending number >=1  and Stating , ending number < Integer.MAX_VALUE 
output constraint 
Display all the numbers between that range

Sample Input
1,10
Sample  Output
2,3,5,7

### Enter link to the question(if question belongs to any online platform) - 
no link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
basic mathematics

**Comment by SarthakKeshari** [comment]
@satyam878,
Kindly add the solution to "Basic codes" folder
Deadline - 29/09/2021

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
following are my accounts:
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234

**Comment by SarthakKeshari** [comment]
> @satyam878, Kindly add the solution to "Basic codes" folder Deadline - 29/09/2021

Deadline over

**Comment by SarthakKeshari** [comment]
@satyam878,
Kindly add the solution to "Basic codes" folder
Deadline - 02/10/2021

**Comment by SarthakKeshari** [comment]
@navjotdadwal,
Kindly add the solution to "Basic codes" folder
Deadline - 02/10/2021

**Comment by navjotdadwal** [comment]
Respected sir
I have a exam from 2p.m to 4p.m after giving exam i will to do rest of the
assigned tasks so sorry for this delay
