### ISSUE TITLE
🌟Website name

### ISSUE THREAD

**Issue by Monica-Chhabria** [SarthakKeshari/Java-Questions-and-Solutions#193]
### Enter your question - 
Contribute a word file to the repository stating the website name and the reason behind selecting that name.
### Enter link to the question(if question belongs to any online platform) - 
NA

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Website Name

**Comment by SarthakKeshari** [comment]
@Monica-Chhabria,
Congratulations🎉 and Thankyou🎁 for coming up with a catchy and innovative title.
I invite you to add more value to the project by creating a pull request.

Title of PR - "🌟Website name declaration"
Body of PR -
Your suggest title
Reason for the title (more than 40 words for the reason will be appreciated)

Also attach a website_name.txt file containing the same details as body of PR.

**Comment by SarthakKeshari** [comment]
Deadline - 05/10/2021

**Comment by Monica-Chhabria** [comment]
Hi @SarthakKeshari can you help me how to raise pr without changing anything in the repo as you are telling to write discription and attach file also in pr. Github is not allowing to raise pr without doing any changes in repo

**Comment by SarthakKeshari** [comment]
@Monica-Chhabria,
Kindly do the changes in the repo. That's only how you can merge it. If any errors occur. I will handle that. Go ahead.

**Comment by Monica-Chhabria** [comment]
In which folder to add txt file @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@Monica-Chhabria,
Outside only, no need to place inside any specific folder
