### ISSUE TITLE
Find the number in sorted rotated array

### ISSUE THREAD

**Issue by MohammedHassan07** [SarthakKeshari/Java-Questions-and-Solutions#195]
### Enter your question - 
Given a sorted rotated array and a target number 
You have to find the target number is present or not

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/search-in-rotated-sorted-array/description/

### Tags for the question(eg - Array, Basic, Stack, etc) -
Array, search

**Comment by MohammedHassan07** [comment]
@SarthakKeshari 
Please assign this issue to me

**Comment by SarthakKeshari** [comment]
@MohammedHassan07,
Kindly add your solution to "leetcode" folder
Deadline - 04/10/2021
