### ISSUE TITLE
Java Abstract Class [Hackerrank]

### ISSUE THREAD

**Issue by neelshah2409** [SarthakKeshari/Java-Questions-and-Solutions#199]
### Enter your question - 
A Java abstract class is a class that can't be instantiated. That means you cannot create new instances of an abstract class. It works as a base for subclasses. You should learn about Java Inheritance before attempting this challenge.

Following is an example of abstract class:

abstract class Book{
    String title;
    abstract void setTitle(String s);
    String getTitle(){
        return title;
    }
}
If you try to create an instance of this class like the following line you will get an error:

Book new_novel=new Book(); 
You have to create another class that extends the abstract class. Then you can create an instance of the new class.

Notice that setTitle method is abstract too and has no body. That means you must implement the body of that method in the child class.

In the editor, we have provided the abstract Book class and a Main class. In the Main class, we created an instance of a class called MyBook. Your task is to write just the MyBook class.

Your class mustn't be public.

### Enter link to the question(if question belongs to any online platform) - 
https://www.hackerrank.com/challenges/java-abstract-class/problem

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Abstract class

**Comment by SarthakKeshari** [comment]
@neelshah2409,
Kindly add your solution to "Hackerrank" folder.
Deadline - 04/10/2021
