### ISSUE TITLE
Check greater than 100 

### ISSUE THREAD

**Issue by dineshparekh11** [SarthakKeshari/Java-Questions-and-Solutions#20]
### Enter your question - 
Check number greater than 100 or not

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic, if else

**Comment by dineshparekh11** [comment]
Kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@dineshparekh11,
Kindly add your solution to "Basic Codes" folder
Deadline 28/09/2021
