### ISSUE TITLE
Lapindrome Strings

### ISSUE THREAD

**Issue by AnuragYadav365** [SarthakKeshari/Java-Questions-and-Solutions#200]
### Enter your question - 
Lapindrome is defined as a string which when split in the middle, gives two halves having the same characters and same frequency of each character. If there are odd number of characters in the string, we ignore the middle character and check for lapindrome. For example abccab is a lapindrome, since the two halves abc and cab have the same characters with same frequency.

### Enter link to the question(if question belongs to any online platform) - 
https://www.codechef.com/problems/LAPIN

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Strings

**Comment by AnuragYadav365** [comment]
Please assign me under hacktoberfest . So I can make a PR under this issue.

**Comment by SarthakKeshari** [comment]
@AnuragYadav365,
Kindly add your solution to "codechef" folder.
Deadline - 04/10/2021
