### ISSUE TITLE
Find Unique Binary String

### ISSUE THREAD

**Issue by satyam878** [SarthakKeshari/Java-Questions-and-Solutions#205]
### Enter your question - 
Given an array of strings nums containing n unique binary strings each of length n, return a binary string of length n that does not appear in nums. If there are multiple answers, you may return any of them.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/find-unique-binary-string/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Bit Manipulation, String

**Comment by satyam878** [comment]
Kindly assign me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@satyam878,
Kindly add you solution to "leetcode" folder
Deadline - 04/10/2021
