### ISSUE TITLE
Finding factorial of a numbers using recursion

### ISSUE THREAD

**Issue by Kaustubh-git** [SarthakKeshari/Java-Questions-and-Solutions#209]
### Enter your question - 
Finding factorial of a numbers using recursion

### Enter link to the question(if question belongs to any online platform) - 
no link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Recursion,Basics

**Comment by Kaustubh-git** [comment]
kindly assign me this issue @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@Kaustubh-git,
This has already been addressed kindly visit "Basic codes" folder
