### ISSUE TITLE
2D Array using Odd number of columns

### ISSUE THREAD

**Issue by Rishi098** [SarthakKeshari/Java-Questions-and-Solutions#210]
### Enter your question - 

If two-dimensional array in java is an array-of-arrays, then it should also support non-symmetric sizes like [2][3], [3],[2], etc..
so try to make 2D Array using Odd number of columns and print

### Enter link to the question(if question belongs to any online platform) - 
no didn't find anything 

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array , Basic

**Comment by Rishi098** [comment]
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@Rishi098,
Kindly elaborate on your question.

**Comment by Rishi098** [comment]
done

**Comment by SarthakKeshari** [comment]
@Rishi098,
Generics are used for this purpose. So using arrays for the purpose will make it very inefficient. Kindly come up with some other question.
