### ISSUE TITLE
Searching element in an array within given range.

### ISSUE THREAD

**Issue by Kaustubh-git** [SarthakKeshari/Java-Questions-and-Solutions#212]
### Enter your question - 
Searching element in an array within given range.

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array,searching

**Comment by Lakshay-Pruthi** [comment]
Can i work on this issue.

**Comment by Kaustubh-git** [comment]
Kindly assign me this issue @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@Lakshay-Pruthi,
Kindly add your solution to "Searching" folder.
Deadline - 04/10/2021

**Comment by SarthakKeshari** [comment]
@Kaustubh-git,
Kindly do not close the Issue. Its still assigned to @Lakshay-Pruthi.

**Comment by Kaustubh-git** [comment]
@SarthakKeshari  
Lakshay's deadline was 04/10/2021 its over now can you reassign to me?

**Comment by SarthakKeshari** [comment]
@Kaustubh-git,
Kindly add your solution to "Searching" folder.
Deadline - 06/10/2021
