### ISSUE TITLE
String searching

### ISSUE THREAD

**Issue by Kaustubh-git** [SarthakKeshari/Java-Questions-and-Solutions#213]
### Enter your question - 
check whether given(target) character is present in a string or not.

### Enter link to the question(if question belongs to any online platform) - 
no link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
String,searching,basic

**Comment by Kaustubh-git** [comment]
kindly assign me this issue @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@Kaustubh-git,
Kindly add your solution to "String Handling" folder
Deadline - 04/10/2021

This Issue will only be counted towards ranking criteria of this repository.

Gentle advice for futher Issues -
A bit more tough questions would be appreciated for Hacktoberfest tag.

**Comment by Kaustubh-git** [comment]
@SarthakKeshari ok
