### ISSUE TITLE
Find a median in two sorted arrays

### ISSUE THREAD

**Issue by ravi0213** [SarthakKeshari/Java-Questions-and-Solutions#225]
**Enter your question -**

Given two sorted arrays of size `n` and `m`, find a median in two sorted arrays. Expected complexity is O(lg(n+m)).

**Enter link to the question(if question belongs to any online platform) -**

https://leetcode.com/problems/median-of-two-sorted-arrays/

**Tags for the question(eg - Array, Basic, Stack, etc.) -**

Binary search

**Comment by ravi0213** [comment]
@SarthakKeshari could you please assign this to me?
Thanks

**Comment by ravi0213** [comment]
> @ravi0213, Kindly follow the issue template.

I have updated the issue description with correct template.

**Comment by SarthakKeshari** [comment]
@ravi0213,
Kindly check the repo. This question has been addressed

**Comment by ravi0213** [comment]
Cool, I will close it then.
