### ISSUE TITLE
Find longest palindromic substring

### ISSUE THREAD

**Issue by ravi0213** [SarthakKeshari/Java-Questions-and-Solutions#227]
### Enter your question - 
Given a string of size n, find the longest palindromic substring. Expected time complexity is O(n\*n) and space complexity is O(n\*n).

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/longest-palindromic-substring/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Dynamic programming

**Comment by SarthakKeshari** [comment]
@ravi0213,
Kindly add your solution to "leetcode" folder.
Deadline - 05/10/2021
