### ISSUE TITLE
Maximum and Minimum value in array

### ISSUE THREAD

**Issue by vish-han** [SarthakKeshari/Java-Questions-and-Solutions#228]
### Enter your question - 
Your are given an array , you have to find the maximum and minimum value in the array.
### Enter link to the question(if question belongs to any online platform) - 
NIL
### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Basic

**Comment by vish-han** [comment]
@SarthakKeshari  Please assign this issue to me ..

**Comment by SarthakKeshari** [comment]
@vish-han,
Kindly add your solution to "" folder.
Deadline - 05/10/2021

This Issue will only be counted towards ranking criteria of this repository.

Gentle advice for futher Issues -
More tough questions would be appreciated for Hacktoberfest tag.

**Comment by vish-han** [comment]
which folder?

**Comment by SarthakKeshari** [comment]
@vish-han,
Really sorry for not specifying
