### ISSUE TITLE
Rotate The Matrix by 90 deg

### ISSUE THREAD

**Issue by vish-han** [SarthakKeshari/Java-Questions-and-Solutions#231]
### Enter your question - 
you have to rotate the 2D array by 90 degrees

### Enter link to the question(if question belongs to any online platform) - 
https://www.geeksforgeeks.org/rotate-a-matrix-by-90-degree-in-clockwise-direction-without-using-any-extra-space/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
2D Array, Matrix

**Comment by vish-han** [comment]
Please assign this issue to me and add the hacktoberfest tag

**Comment by SarthakKeshari** [comment]
@vish-han,
Kindly add your solution to "GeeksForGeeks" folder.
Deadline - 04/10/2021

**Comment by vish-han** [comment]
@SarthakKeshari please add hacktoberfest tag

**Comment by SarthakKeshari** [comment]
@vish-han,
I wish to add one more point, you have a consistent contribution to the repository. I would be glad if you could come up with questions that are completely created by you or from your college assignments. That will help the repository to have a very valuable input from your end.

**Comment by SarthakKeshari** [comment]
@vish-han,
All the best
