### ISSUE TITLE
 Container With Most Water

### ISSUE THREAD

**Issue by Lakshay-Pruthi** [SarthakKeshari/Java-Questions-and-Solutions#232]
### Enter your question - 
Given n non-negative integers a1, a2, ..., an , where each represents a point at coordinate (i, ai). n vertical lines are drawn such that the two endpoints of the line i is at (i, ai) and (i, 0). Find two lines, which, together with the x-axis forms a container, such that the container contains the most water.

Notice that you may not slant the container.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/container-with-most-water/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Two pointer

![leetcode](https://user-images.githubusercontent.com/91469717/135896376-eb5e8b5f-1a63-4564-a716-c35590155c74.png)

This is a very good question and I think every one should give it a try!!

**Comment by Lakshay-Pruthi** [comment]
@SarthakKeshari can you assign it to me??

**Comment by SarthakKeshari** [comment]
@Lakshay-Pruthi,
Kindly add your solution to "leetcode" folder
Deadline - 05/10/2021
