### ISSUE TITLE
Sort Colors

### ISSUE THREAD

**Issue by Lakshay-Pruthi** [SarthakKeshari/Java-Questions-and-Solutions#235]
### Enter your question - 
Sort colors

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/sort-colors/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Arrays
![leetcode 2](https://user-images.githubusercontent.com/91469717/135902238-97378a75-b73b-4fa4-8bf3-b5c1eedc9df7.png)

**Comment by Lakshay-Pruthi** [comment]
added this new one because previous one was already in the folder @SarthakKeshari assign this to me.

**Comment by SarthakKeshari** [comment]
@Lakshay-Pruthi,
Firstly, very glad to see such a responsible behaviour.
Kindly add your solution to "leetcode" folder.
Deadline - 05/10/2021

**Comment by Lakshay-Pruthi** [comment]
@SarthakKeshari here it is #251 .
