### ISSUE TITLE
LRU Cache

### ISSUE THREAD

**Issue by Sakshamgupta90** [SarthakKeshari/Java-Questions-and-Solutions#237]
### Enter your question - 
LRU Cache

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/lru-cache/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Linked List

@SarthakKeshari Can you please assign me this issue?

**Comment by SarthakKeshari** [comment]
@Sakshamgupta90,
Kindly add your solution to "leetcode" folder.
Deadline - 05/10/2021
