### ISSUE TITLE
Predict the winner

### ISSUE THREAD

**Issue by ravi0213** [SarthakKeshari/Java-Questions-and-Solutions#250]
### Enter your question - 
Two players are playing a game with a given array of size `n`. Both players make their turn alternatively. In each turn, a player will pick the array element from either end and add it to their score. Assuming both players play this game optimally, we need to tell if player 1 wins or not. If there is a tie then player 1 wins.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/predict-the-winner/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Dynamic programming, Google interview

**Comment by ravi0213** [comment]
@SarthakKeshari could you please assign this to me?

**Comment by SarthakKeshari** [comment]
@ravi0213,
Kindly add your solution to "leetcode" folder
Deadline - 06/10/2021
