### ISSUE TITLE
[Java End-of-file]

### ISSUE THREAD

**Issue by Harsh-bartariya** [SarthakKeshari/Java-Questions-and-Solutions#264]
### Enter your question - 
"In computing, End Of File (commonly abbreviated EOF) is a condition in a computer operating system where no more data can be read from a data source.
The challenge here is to read  lines of input until you reach EOF, then number and print all  lines of content.

Hint: Java's Scanner.hasNext() method is helpful for this problem.

Input Format

Read some unknown  lines of input from stdin(System.in) until you reach EOF; each line of input contains a non-empty String.

Output Format

For each line, print the line number, followed by a single space, and then the line content received as input.

Sample Input

Hello world
I am a file
Read me until end-of-file.

Sample Output
1 Hello world
2 I am a file
3 Read me until end-of-file.

### Enter link to the question(if question belongs to any online platform) - Hackerrank
https://www.hackerrank.com/challenges/java-end-of-file/problem

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
String

**Comment by Harsh-bartariya** [comment]
Please assign this issue to me. i can solve it

**Comment by SarthakKeshari** [comment]
@Harsh-bartariya,
Kindly add your solution to "hackerrank" folder
Deadline - 06/10/2021

**Comment by Harsh-bartariya** [comment]
Ok sir thank you.

**Comment by Harsh-bartariya** [comment]
Sir firstly i solved this question on hackerrank
sir is it against the guidelines and the code of conduct 
i can make PR this time but this just came in my mind can you please clarify it.....please

**Comment by SarthakKeshari** [comment]
@Harsh-bartariya,
The repository support an original submission(completely written by you). It does not matter whether it was done just now was previously. The guidelines only says to be true and original.

**Comment by SarthakKeshari** [comment]
@Harsh-bartariya,
One more point I wish to add.
This Issue will be counted towards ranking criteria of this repository.

Gentle advice for futher Issues -
Medium and hard level questions will be given preference for Hacktoberfest tag.

**Comment by Harsh-bartariya** [comment]
Yes sir thank you...the solution is completely written by me and i can explain the logic as well 
and again thanks for the lables you added
