### ISSUE TITLE
🔴🟨 Call for Logo Designing - Phase 2 🟨🔴

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#276]
### Discussed in https://github.com/SarthakKeshari/Java-Questions-and-Solutions/discussions/275

<div type='discussions-op-text'>

<sup>Originally posted by **SarthakKeshari** October  6, 2021</sup>
***
# Hello team, 👋

### 🌄Opening a new way into this project to make it more user-friendly and to start this I wish to have your suggestions. #Letsthinktogether🤩

<hr>

### I am elated to call upon everyone to design a logo for the website (***only one logo per participant***). We'll accept logo submissions till 2AM(10/10/2021)

- The participant whose logo gets selected will get the chance to contribute an image file along with a word file to the repository stating the inspiration and the reason behind creating the contributed logo.
- The selected participant will be given **level 2 tag as well as hacktoberfest-accepted tag** for this contribution.

## Submission process - Attach your created logo image in the comment section below

#️⃣Winning #️⃣EverySuggestionMatters</div>

**Comment by SarthakKeshari** [comment]
> @SarthakKeshari Can I update the logo after making some changes

Yes, You can make the changes or even change the logo any number of times before the deadline.

**Comment by MohammedHassan07** [comment]
@SarthakKeshari 
![Uploading IMG-20211009-WA0017.jpg…]()

Updated,
This is brighter than previous one

**Comment by MohammedHassan07** [comment]
@SarthakKeshari 
![IMG-20211009-WA0017](https://user-images.githubusercontent.com/90477795/136661064-027eb200-7de5-4966-8a33-e25e55576971.jpg)

Updated the logo,
Brighter than previous one

**Comment by SarthakKeshari** [comment]
@MohammedHassan07,

### NOTE - Coding Library Website's theme is black, white and grey.

An advice - The logo will be of max. size of almost 1 inch by 1 inch as you must have seen on different websites. Or you can see this github logo. So try making a logo with as minimal details as possible, so that even if its very small it can get attention.



![image](https://user-images.githubusercontent.com/55992140/136663038-ca8b5bf2-1fd2-4fdb-b12c-d5279606d760.png)


I guess this trick will help to improve or come up with something new. Still 6 hours are left. You may give it a try.

**Comment by SarthakKeshari** [comment]
@MohammedHassan07,
😃 I am glad to announce that your logo✔ has been selected as the website logo for this project.
Kindly create an issue with the title "🌟Website logo" and get it assigned in order to create a PR to contribute a .png file and a word file(stating the inspiration and the reason behind creating the contributed logo) to the repository.
