### ISSUE TITLE
Semi sort 1

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#28]
### Enter your question - 
Write a program to sort half of the array in ascending and second half in descending or vice versa depending on users choice.
AD - Ascending then descending
DA - Descending then ascending

Sample test case - 
Input - 
Enter sorting style: AD
Enter number of elements in the array: 5
Numbers: 1 4 2 4 2

Output - 
Semi-sorted: 1 2 4 4 2

Explaination - 
Array -> 1 4 2 4 2
Part-one -> 1 4 2 -> (Sorting part-one in ascending order since user enter AD) -> 1 2 4
Part-two -> 4 2 -> (Sorting part-two in descending order since user enter AD) -> 4 2
Therefore, output -> 1 2 4 4 2

### Enter link to the question(if question belongs to any online platform) - 
No Link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, sorting

**Comment by Ln11211** [comment]
@SarthakKeshari  I want to try this, please assign this to me...

**Comment by Ln11211** [comment]
@SarthakKeshari is is possible to add this under Hacktoberfest ?

**Comment by SarthakKeshari** [comment]
@Ln11211,
Go ahead, Kindly place your solution in "Sorting" folder.
Deadline - 01/10/2021

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
following are my accounts:
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234

**Comment by Ln11211** [comment]
@SarthakKeshari sir, this sure is a tough one, but I have completed it..
is the hactoberfest officially started ? or should I wait until it starts ?

**Comment by Ln11211** [comment]
@navjotdadwal, I have already comleted the code, and I will create a pull request once it's 1st of september in my timezone, just waiting for the hactoberfest to start...

**Comment by SarthakKeshari** [comment]
> @SarthakKeshari sir, this sure is a tough one, but I have completed it.. is the hactoberfest officially started ? or should I wait until it starts ?

Go ahead, contribute now.
