### ISSUE TITLE
Max Chunks To Make Sorted II

### ISSUE THREAD

**Issue by nik132-eng** [SarthakKeshari/Java-Questions-and-Solutions#283]
### Enter your question - 
You are given an integer array arr.

We split arr into some number of chunks (i.e., partitions), and individually sort each chunk. After concatenating them, the result should equal the sorted array.

Return the largest number of chunks we can make to sort the array.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/max-chunks-to-make-sorted-ii/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array , Stack ,greedy

**Comment by nik132-eng** [comment]
Can you please assign me this issue for hacktoberfest

**Comment by SarthakKeshari** [comment]
@nik132-eng,
Kindly add your solution to "leetcode" folder.
Deadline - 07/10/2021
