### ISSUE TITLE
Median of 2 sorted arrays.

### ISSUE THREAD

**Issue by Onkar627** [SarthakKeshari/Java-Questions-and-Solutions#285]
### Enter your question - 

Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.
Input: nums1 = [1,3], nums2 = [2]
Output: 2.00000
Explanation: merged array = [1,2,3] and median is 2.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/median-of-two-sorted-arrays/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Arrays,Searching

**Comment by SarthakKeshari** [comment]
@Onkar627,
Kindly go through the repo. This issue is already addressed
