### ISSUE TITLE
Course Schedule

### ISSUE THREAD

**Issue by ravi0213** [SarthakKeshari/Java-Questions-and-Solutions#287]
### Enter your question - 
There are N courses and they are labeled from 0 to N-1. You are also given a list of pairs (X, Y), indicates, you must take a course Y before X.
You need to answer if it is possible to finish all courses or not.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/course-schedule/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Topological Sorting, Cycle detection in graph.

**Comment by SarthakKeshari** [comment]
@ravi0213,
Kindly add your solution to "leetcode" folder.
Deadline - 07/10/2021
