### ISSUE TITLE
Best Time to Buy and Sell Stock III

### ISSUE THREAD

**Issue by Onkar627** [SarthakKeshari/Java-Questions-and-Solutions#290]
### Enter your question - 
You are given an array prices where prices[i] is the price of a given stock on the ith day.

Find the maximum profit you can achieve. You may complete at most two transactions.

Note: You may not engage in multiple transactions simultaneously (i.e., you must sell the stock before you buy again).
### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/
### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array

**Comment by SarthakKeshari** [comment]
@Onkar627,
Kindly add your solution to "leetcode" folder.
Deadline - 08/10/2021
