### ISSUE TITLE
Power set 

### ISSUE THREAD

**Issue by 2devyank** [SarthakKeshari/Java-Questions-and-Solutions#293]
### Enter your question - 
Generate Power set using Bitwise operator
Input="abc".
output="","a","b","c","ac","ab","bc","abc".

**Comment by SarthakKeshari** [comment]
@2devyank,
Kindly elaborate in comments that how you are going to approach this problem.

**Comment by 2devyank** [comment]
@SarthakKeshari 
## Question 
Generate Power set using Bitwise operator
## Sample Case
Input="ab"
Output="","a","b","ab"
## Approach
Basically what we have to do is check whether a bit is set or not if a bit is set then will print that character

So if n is the length of string given , then the number of subsets of that string is 2^n.
Therefore ,will be running two loop firstly will run the outer loop from 0 to (2^n)-1 and inside will run loop of the length of string and will check using bitwise operator if a bit is set or not ,if bit is set then will print that character
