### ISSUE TITLE
Fibonacci sequence

### ISSUE THREAD

**Issue by MiryamVicente** [SarthakKeshari/Java-Questions-and-Solutions#299]
### Enter your question - 
Make the Fibonacci sequence. It consists of a series of natural numbers that are added by 2, starting from 0 and 1 (the Fibonacci sequence is carried out by always adding the last 2 numbers), like that:

0,1,1,2,3,5,8,13,21,34...

### Enter link to the question(if question belongs to any online platform) - 
Your answer

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic, Conditionals

**Comment by SarthakKeshari** [comment]
@MiryamVicente,
Kindly add your solution to "Basic Codes" folder.
Deadline - 08/10/2021

This Issue will only be counted towards ranking criteria of this repository.

Gentle advice for futher Issues -
A bit more questions will be given preference for Hacktoberfest tag.
