### ISSUE TITLE
Quadratic

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#3]
### Enter your question - 
Find the roots of the quadratic Equation

### Enter link to the question(if question belongs to any online platform) - 
NO link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Maths, Datatypes

**Comment by Krush2311** [comment]
hello sir, kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@Krush2311,
Go ahead, Kindly add your solution to "Basic Codes" folder.
Deadline - 30/09/2021
