### ISSUE TITLE
Letter F

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#305]
### Enter your question - 
Write a program to print letter F exactly as shown below -

![image](https://user-images.githubusercontent.com/55992140/136354949-32b109ba-dc93-4977-ac3d-8325094a9dd9.png)

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
loops, pattern printing

**Comment by iravimandalia** [comment]
@SarthakKeshari, I have added my solution. :)
