### ISSUE TITLE
Letter K

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#309]
### Enter your question - 
Write a program to print letter K exactly as shown below -

![image](https://user-images.githubusercontent.com/55992140/136355893-5489ccc7-0de6-47b6-a1ff-7612442c6bd6.png)

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
loops, pattern printing

**Comment by limitlessdeveloper** [comment]
Hi @SarthakKeshari, please assign this issue to me, Thanks!

**Comment by SarthakKeshari** [comment]
@limitlessdeveloper,
Kindly add your solution to "Pattern Printing" folder.
Deadline - 09/10/2021
