### ISSUE TITLE
Maximum Product of Three Numbers

### ISSUE THREAD

**Issue by nik132-eng** [SarthakKeshari/Java-Questions-and-Solutions#321]
### Enter your question - 
Given an integer array nums, find three numbers whose product is maximum and return the maximum product.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/maximum-product-of-three-numbers/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Math ,sorting

**Comment by SarthakKeshari** [comment]
Surely, You can practice here.
