### ISSUE TITLE
Largest Number At Least Twice of Others

### ISSUE THREAD

**Issue by nik132-eng** [SarthakKeshari/Java-Questions-and-Solutions#323]
### Enter your question - 
You are given an integer array nums where the largest integer is unique.

Determine whether the largest element in the array is at least twice as much as every other number in the array. If it is, return the index of the largest element, or return -1 otherwise.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/largest-number-at-least-twice-of-others/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Sorting

**Comment by SarthakKeshari** [comment]
@nik132-eng,
Kindly note - 
Not more than 2 questions can be assigned to a contributor at a time.
