### ISSUE TITLE
Mathematical operation- Subtraction

### ISSUE THREAD

**Issue by Kaustubh-git** [SarthakKeshari/Java-Questions-and-Solutions#339]
### Enter your question - 
Performing subtraction of two numbers using parallel programming

### Enter link to the question(if question belongs to any online platform) - 
no link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
rmi,server,basic,client, parallel programming

**Comment by Kaustubh-git** [comment]
Kindly assign me this issue @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@Kaustubh-git,
Kindly create folder "Parallel Programming" folder and add your solution to it.
Deadline - 09/10/2021
