### ISSUE TITLE
Special Number

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#34]
### Enter your question - 
Write a program to check if a number is Special or not

Explaination - 
A number is said to be special if the sum of the factorial of its digits is equal to the original number.(Make program modular by creating user-defined functions. eg- factorial(), sum())

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Number theory, functions, maths

**Comment by dineshparekh11** [comment]
Kindly give me #34 issue to me

**Comment by SarthakKeshari** [comment]
@dineshparekh11,
Kindly create a folder "Number Theory" and place your solution in it.
Deadline - 01/10/2021

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
following are my accounts:
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
