### ISSUE TITLE
Factorial of a number (recursively)

### ISSUE THREAD

**Issue by MohammedHassan07** [SarthakKeshari/Java-Questions-and-Solutions#35]
### Enter your question - 
Find the Factorial of a number using recursion.

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic

**Comment by MohammedHassan07** [comment]
@SarthakKeshari 
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@MohammedHassan07,
This has already been addressed and has been merged
