### ISSUE TITLE
Missing numbers

### ISSUE THREAD

**Issue by RashidNepal** [SarthakKeshari/Java-Questions-and-Solutions#361]
### Enter your question - 
Given an array nums containing n distinct numbers in the range [0, n], return the only number in the range that is missing from the array.

### Enter link to the question(if question belongs to any online platform) - 
[Missing numbers](https://leetcode.com/problems/missing-number/)

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array,Sorting

**Comment by RAshid602** [comment]
Done.

**Comment by SarthakKeshari** [comment]
@RAshid602,
Kindly add your solution to "leetcode" folder.
Deadline - 10/10/2021
