### ISSUE TITLE
Search a sorted array which is rotated

### ISSUE THREAD

**Issue by venkatsgithub1** [SarthakKeshari/Java-Questions-and-Solutions#363]
### Enter your question - 
A sorted array is rotated by some number, we need to search for a given number in the array.

### Enter link to the question(if question belongs to any online platform) - 
I was studying this in Educative.io, video link: [Link to Problem explanation](https://www.youtube.com/watch?v=uufaK2uLnSI&list=PL2_aWCzGMAwL3ldWlrii6YeLszojgH77j&index=7&t=399s)

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array

**Comment by SarthakKeshari** [comment]
I appreciate that you came up with a question implementation on the topic that you are learning.
