### ISSUE TITLE
Delete Node in a BST

### ISSUE THREAD

**Issue by sRahul-00** [SarthakKeshari/Java-Questions-and-Solutions#365]
Enter your question - 
Delete Node in a BST

 Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/delete-node-in-a-bst/

 Tags for the question(eg - Array, Basic, Stack, etc.) - 
Binary Search Tree

**Comment by sRahul-00** [comment]
shall I work on this?

**Comment by RAshid602** [comment]
@sRahul-00  kindly set the Question title.
you can find edit option on Top right corner.

**Comment by sRahul-00** [comment]
@RAshid602 @SarthakKeshari done with the issue...
