### ISSUE TITLE
Bitwise AND of Numbers Range

### ISSUE THREAD

**Issue by satyam878** [SarthakKeshari/Java-Questions-and-Solutions#382]
### Enter your question - 
Given two integers left and right that represent the range [left, right], return the bitwise AND of all numbers in this range, inclusive.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/bitwise-and-of-numbers-range/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
bit-manipulation

**Comment by satyam878** [comment]
Kindly assign me this task @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@satyam878,
Kindly add your solution to "leetcode" folder
Deadline - 11/10/2021
