### ISSUE TITLE
Longest SubString with Distinct Characters

### ISSUE THREAD

**Issue by venkatsgithub1** [SarthakKeshari/Java-Questions-and-Solutions#388]
### Enter your question - 
A String is provided as input, we need to find out the longest substring of the given string with distinct characters.

### Enter link to the question(if question belongs to any online platform) - 
I was studying this in Educative.io.

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Sliding Window, Strings.

**Comment by SarthakKeshari** [comment]
@venkatsgithub1,
Kindly add your solution to "Pattern Printing" folder.
Deadline - 12/10/2021
