### ISSUE TITLE
Partition Labels

### ISSUE THREAD

**Issue by nik132-eng** [SarthakKeshari/Java-Questions-and-Solutions#390]
### Enter your question - 
You are given a string s. We want to partition the string into as many parts as possible so that each letter appears in at most one part.

Return a list of integers representing the size of these parts.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/partition-labels/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Hash table, String

**Comment by SarthakKeshari** [comment]
@nik132-eng,
Kindly add your solution to "leetcode" folder.
Deadline - 12/10/2021
