### ISSUE TITLE
Website logo

### ISSUE THREAD

**Issue by MohammedHassan07** [SarthakKeshari/Java-Questions-and-Solutions#395]
### Enter your question - 
Providing the logo for website

### Enter link to the question(if question belongs to any online platform) - 
No link

**Comment by MohammedHassan07** [comment]
@SarthakKeshari 
In which folder should I place the .PNG file and word file

**Comment by MohammedHassan07** [comment]
@SarthakKeshari 
Kindly check the logo


![Final](https://user-images.githubusercontent.com/90477795/137015039-170d3cf9-a06d-4071-85cf-cec906c34cc5.png)

**Comment by SarthakKeshari** [comment]
@MohammedHassan07,
Amazing

**Comment by SarthakKeshari** [comment]
@MohammedHassan07,
Thankyou🎁 for coming up with such an aesthetic and innovative logo.
I invite you to add more value to the project by creating a pull request.

Title of PR - "🌟Website logo declaration"
Body of PR should contain -
Website title
Logo Image file
Inspiration and the reason behind creating the contributed logo(more than 40 words for the reason will be appreciated)

Also attach a website_name.txt file containing the same details as body of PR along with your image file.

**Comment by SarthakKeshari** [comment]
@MohammedHassan07,
Directly in the "Java-Questions-and-Solutions" folder.
