### ISSUE TITLE
MoveZeros

### ISSUE THREAD

**Issue by vyom18** [SarthakKeshari/Java-Questions-and-Solutions#398]
### Enter your question - 
Given an integer array nums, move all 0's to the end of it while maintaining the relative order of the non-zero elements.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/explore/interview/card/top-interview-questions-easy/92/array/567/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array

**Comment by SarthakKeshari** [comment]
@vyom18,
Kindly request for assigning it and only once its assigned, you may created the PR.
Since its happening for the first time, I will accept it.
