### ISSUE TITLE
Sorting an array

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#4]
### Enter your question - 
Take 10 numbers as input from the user and sort it

### Enter link to the question(if question belongs to any online platform) - 
NO link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
sorting, array

### Question belongs to which section/subsection(eg - Arrays/1D Arrays) -
Arrays/1D Arrays

**Comment by SB2318** [comment]
I want to work on this issue. Please assign it to me.

**Comment by SarthakKeshari** [comment]
@SB2318,
Kindly add your solution to "Basic Codes" folder.
Deadline - 30/09/2021

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 can resolve this issue
following are my accounts:
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234

**Comment by SarthakKeshari** [comment]
> @SB2318, Kindly add your solution to "Basic Codes" folder. Deadline - 30/09/2021

Deadline over

**Comment by SarthakKeshari** [comment]
@navjotdadwal,
Go ahead, Kindly add your solution to "Basic Codes" folder.
Deadline - 02/10/2021
