### ISSUE TITLE
Palindrome Prime

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#41]
### Enter your question - 
Write a program to check a number for palindrome prime.

Palindrome - A palindromic number is a number (such as 16461) that remains the same when its digits are reversed. 
Prime - a whole number greater than 1 that cannot be exactly divided by any whole number other than itself and 1

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Loops. Number Theory

**Comment by dineshparekh11** [comment]
Kindly Give #41 Write a program to check a number for palindrome prime issue to me

**Comment by SarthakKeshari** [comment]
@dineshparekh11,
Kindly add you solution to "Number Theory" folder.
Deadline - 01/10/2021

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
following are my accounts:
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
