### ISSUE TITLE
Construct Binary Search Tree from Preorder Traversal

### ISSUE THREAD

**Issue by satyam878** [SarthakKeshari/Java-Questions-and-Solutions#416]
### Enter your question - 
Given an array of integers preorder, which represents the preorder traversal of a BST (i.e., binary search tree), construct the tree and return its root.

It is guaranteed that there is always possible to find a binary search tree with the given requirements for the given test cases.

A binary search tree is a binary tree where for every node, any descendant of Node.left has a value strictly less than Node.val, and any descendant of Node.right has a value strictly greater than Node.val.

A preorder traversal of a binary tree displays the value of the node first, then traverses Node.left, then traverses Node.right.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Binary Search Tree, Stack, Binary Tree

**Comment by SarthakKeshari** [comment]
@satyam878,
Kindly add your solution to "leetcode" folder.
Deadline - 13/10/2021
