### ISSUE TITLE
Longest Palindromic Substring

### ISSUE THREAD

**Issue by aarzoopundir** [SarthakKeshari/Java-Questions-and-Solutions#418]
### Enter your question - 
Given a string s, return the longest palindromic substring in s.
Input: s = "babad"
Output: "bab"

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/longest-palindromic-substring/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
String

**Comment by aarzoopundir** [comment]
The other solution was using dynamic programming and this solution is
better than dynamic programming

**Comment by SarthakKeshari** [comment]
@aarzoopundir,
Program updation and multiple responses will be considered once the website it up. For now one program for a question is only entertained.

**Comment by aarzoopundir** [comment]
Okk
