### ISSUE TITLE
Reverse string without using inbuilt function

### ISSUE THREAD

**Issue by darshanr27** [SarthakKeshari/Java-Questions-and-Solutions#42]
### Enter your question - 
Write a java program to reverse the string without using the inbuilt function.

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
String, Basic, Looping

**Comment by darshanr27** [comment]
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@darshanr27,
Kindly add your solution to "String handling" folder.
Deadline - 01/10/2021
