### ISSUE TITLE
nth smallest element in Binary search tree 

### ISSUE THREAD

**Issue by mahesh-11102** [SarthakKeshari/Java-Questions-and-Solutions#43]
###  Write a Java program to identify the kth smallest element in the binary search tree. 
Since the tree is Binary search tree, so we need to go to the `leftmost node` and start counting to right if count is equal to k print node 

### Enter link to the question(if question belongs to any online platform) - 
`N/A`

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
trees, LinkedList ,  Binary Tree

`for example` : 
![image](https://user-images.githubusercontent.com/77436328/135508184-e297e119-6d96-4f87-8302-ac3f6cb53020.png)

As a part of `Hacktoberfest`, @SarthakKeshari  please assign this issue to me

**Comment by SarthakKeshari** [comment]
@mahesh-11102,
Considering this question will be attempted using Linked list and not simple array, I am assigning it under `Hacktoberfest`
Kindly place your solution in "Data Structures/Trees/Binary Trees" folder.
Deadline - 03/10/2021

**Comment by mahesh-11102** [comment]
Thank you @SarthakKeshari sir
