### ISSUE TITLE
Important announcement

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#439]
### Discussed in https://github.com/SarthakKeshari/Java-Questions-and-Solutions/discussions/438

<div type='discussions-op-text'>

<sup>Originally posted by **SarthakKeshari** October 14, 2021</sup>
Hey Team,
As per informed by one of the contributors that the project show to have been excluded from Hacktoberfest. So the project won't be accepting any issues and PR under Hacktoberfest tag.

### I welcome all who wish to make this aim a success</div>

**Comment by nik132-eng** [comment]
sir, can you suggest any repo for Oktoberfest for beginners at open source.
