### ISSUE TITLE
The longest ascending sequence

### ISSUE THREAD

**Issue by erickcernarequejo** [SarthakKeshari/Java-Questions-and-Solutions#47]
Write a program that reads an array of ints and outputs the length of the longest sequence in strictly ascending order. Elements of the sequence must go one after another. A single number is assumed to be an ordered sequence with the length = 1.

### Enter link to the question(if question belongs to any online platform) - 
```N/A```

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Basic

```Example : ```

![example](https://user-images.githubusercontent.com/8706329/135546399-2cdd76d3-d4b5-450a-b52b-5cc540004223.png)

As a part of Hacktoberfest, @SarthakKeshari please assign this issue to me

**Comment by SarthakKeshari** [comment]
@erickcernarequejo,
Go ahead, Kindly add your solution in "Arrays/1D Arrays" folder.
Deadline - 02/10/2021

**Comment by aadityasinha-dotcom** [comment]
Can I work on this issue?

**Comment by erickcernarequejo** [comment]
> @erickcernarequejo, Go ahead, Kindly add your solution in "Arrays/1D Arrays" folder. Deadline - 02/10/2021

Thank you @SarthakKeshari

**Comment by SarthakKeshari** [comment]
> Can I work on this issue?

You may create a new issue since this is alreadt assigned

**Comment by aadityasinha-dotcom** [comment]
> > Can I work on this issue?
> 
> You may create a new issue since this is alreadt assigned

What type of issues I can create?

**Comment by SarthakKeshari** [comment]
> > > Can I work on this issue?
> > 
> > 
> > You may create a new issue since this is alreadt assigned
> 
> What type of issues I can create?

You can create your own question and comment to get assigned

**Comment by aadityasinha-dotcom** [comment]
> > > > Can I work on this issue?
> > > 
> > > 
> > > You may create a new issue since this is alreadt assigned
> > 
> > 
> > What type of issues I can create?
> 
> You can create your own question and comment to get assigned

Can I add a question that was on codechef or codeforces or any other platforms?

**Comment by SarthakKeshari** [comment]
> > > > > Can I work on this issue?
> > > > 
> > > > 
> > > > You may create a new issue since this is alreadt assigned
> > > 
> > > 
> > > What type of issues I can create?
> > 
> > 
> > You can create your own question and comment to get assigned
> 
> Can I add a question that was on codechef or codeforces or any other platforms?

Yes, but it should be a medium level or above question as well as there are more strict review rules for them, even after successful merge they will be reviewed again by the team. Plagarism might lead to ban.

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue
