### ISSUE TITLE
Birthday Cake Candles

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#5]
### Enter your question - 
You are in charge of the cake for a child's birthday. You have decided the cake will have one candle for each year of their total age. They will only be able to blow out the tallest of the candles. Count how many candles are tallest.

### Enter link to the question(if question belongs to any online platform) - 
https://www.hackerrank.com/challenges/birthday-cake-candles/problem

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic, array

### Question belongs to which section/subsection(eg - Arrays/1D Arrays) -
Hackerrank

**Comment by Ln11211** [comment]
Hello @SarthakKeshari sir, Kindly assign this issue to me...

**Comment by SarthakKeshari** [comment]
@Ln11211,
Kindly add your solution to "Basic Codes" folder.
Deadline - 30/09/2021

Hacktoberfest tag will be applicable from 1st October

**Comment by Ln11211** [comment]
Hello @SarthakKeshari sir, is this issue no more under the hacktoberfest tag ?
