### ISSUE TITLE
Max Length Of SubArray

### ISSUE THREAD

**Issue by aadityasinha-dotcom** [SarthakKeshari/Java-Questions-and-Solutions#50]
### Enter your question - 
Write a program that read an array of integers and an integer k and outputs the length of maximum length of sub array with sum equals to k. If there is no sub array length > 1 and the element k is present in the array then the output = 1.
### Enter link to the question(if question belongs to any online platform) - 
`N/A`

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Basic

`Example:`

![hacktober](https://user-images.githubusercontent.com/75474786/135561110-147054e4-91b9-46fd-9e2e-f88d790632b3.PNG)
As a part of Hacktoberfest, @SarthakKeshari please assign this issue to me

**Comment by SarthakKeshari** [comment]
@aadityasinha-dotcom,
Good question just one thing that needs to be clarified in the question, what if neither k is present in the array nor the sum of sub-array sums up to k.

**Comment by aadityasinha-dotcom** [comment]
Then it will print -1.

> @aadityasinha-dotcom, Good question just one thing that needs to be clarified in the question, what if neither k is present in the array nor the sum of sub-array sums up to k.

Then it will print -1.

**Comment by aadityasinha-dotcom** [comment]
@SarthakKeshari Can I work in this Issue for Hactoberfest 2021?

**Comment by SarthakKeshari** [comment]
@aadityasinha-dotcom,
Go ahead, Kindly save your solution to "Arrays/ 1D Arrays" folder.
Deadline - 02/10/2021
