### ISSUE TITLE
Palindrome String

### ISSUE THREAD

**Issue by satyam878** [SarthakKeshari/Java-Questions-and-Solutions#53]
### Enter your question - 
Given a string str, we need to check whether the given string is palindrome or not
A Palindrome string is a such string that reversing it gives the same string.

### Enter link to the question(if question belongs to any online platform) - 
Not Any

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
String

**Comment by satyam878** [comment]
Please approve the question @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@satyam878,
Go ahead, Kindly place your solution in "String handling" folder.
Deadline - 02/10/2021
