### ISSUE TITLE
there is no searching and sorting question

### ISSUE THREAD

**Issue by vish-han** [SarthakKeshari/Java-Questions-and-Solutions#54]
@SarthakKeshari , Please assign this issue to me
I will do this in just 2 hours, I will feel very motivated if u give this issue to me

**Comment by SarthakKeshari** [comment]
@vish-han,
Kindly look into #22 and complete it or close it. Else it will be counted as rejected

**Comment by vish-han** [comment]
can u assign this issue to me now??
plzz add the hacktoberfest tag

**Comment by SarthakKeshari** [comment]
In case you don't find an active issue to claim. Create your own and I will assign.
Refere Contributing guildlines for more details
