### ISSUE TITLE
🔴⭕Update for all - Step 1⭕🔴

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#57]
### Discussed in https://github.com/SarthakKeshari/Java-Questions-and-Solutions/discussions/56

<div type='discussions-op-text'>

<sup>Originally posted by **SarthakKeshari** October  1, 2021</sup>
***
# Hello team, 👋
### Your amazing efforts can be seen from very first day and this is really motivating and creates positive project building spirit.
***

### 🌄Opening a new way into this project to make it more user-friendly and to start this I wish to have your suggestions. #Letsthinktogether🤩

<br>

### I am elated to call upon everyone to suggest a name for the website (***only one name per participant***). We'll collect the ideas for name till 2AM(03/10/2021)

- The participant whose suggested name gets selected will get the chance to contribute a word file to the repository stating the website name and the reason behind selecting that name.
- The selected participant will be given **level 2 tag as well as hacktoberfest-accepted tag** for this contribution.

#️⃣Winning #️⃣EverySuggestionMatters</div>

**Comment by MohammedHassan07** [comment]
@SarthakKeshari 
Website name : Learn to Code

**Comment by Monica-Chhabria** [comment]
Website : Coding Library
Since library is a collection of books, This website would be collection of useful codes

**Comment by iamsunil25** [comment]
website : crackJavaInterview or boostJavaInterview
all questions belongs to java

**Comment by iamsunil25** [comment]
hey @SarthakKeshari how can someone get level x, level y, level z, level 5?

**Comment by SarthakKeshari** [comment]
> hey @SarthakKeshari how can someone get level x, level y, level z, level 5?

By coming up with a proper real world issue proposal to solve.

**Comment by SarthakKeshari** [comment]
@Monica-Chhabria, 👏
😃 I am glad to announce that that "Coding Library"✔ has been selected as the website name for this project.
Kindly create an issue with the title "🌟Website name" to contribute a word file to the repository stating the website name and the reason behind selecting that name.
