### ISSUE TITLE
Prime Game

### ISSUE THREAD

**Issue by SarthakKeshari** [SarthakKeshari/Java-Questions-and-Solutions#6]
### Enter your question - 
Chef and Divyam are playing a game with the following rules:

First, an integer X! is written on a board.
Chef and Divyam alternate turns; Chef plays first.
In each move, the current player should choose a positive integer D which is divisible by up to Y distinct primes and does not exceed the integer currently written on the board. Note that 1 is not a prime.
D is then subtracted from the integer on the board, i.e. if the integer written on the board before this move was A, it is erased and replaced by A−D.
When one player writes 0 on the board, the game ends and this player wins.
Given X and Y, determine the winner of the game.

### Enter link to the question(if question belongs to any online platform) - 
https://www.codechef.com/problems/PRIGAME

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
functions

### Question belongs to which section/subsection(eg - Arrays/1D Arrays) -
CodeChef

**Comment by Ln11211** [comment]
Hello @SarthakKeshari sir, can I please do this, I already have a solution in my mind ?, Kindly assign this issue to me..

**Comment by SarthakKeshari** [comment]
@Ln11211 
Cannot assign more than 2 issues at a time under the same person. You may claim the same after 6 PM. 29/09/2021 if no one claims it.

**Comment by Diegoslourenco** [comment]
@SarthakKeshari can you assign this to me?

**Comment by SarthakKeshari** [comment]
@Diegoslourenco,
Kindly add your solution to "CodeChef" folder.
Deadline - 1/10/2021

Hacktoberfest tag will be applicable from 1st October

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
following are my accounts:
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
