### ISSUE TITLE
Cyclic sort

### ISSUE THREAD

**Issue by MohammedHassan07** [SarthakKeshari/Java-Questions-and-Solutions#61]
### Enter your question -
If array is given from 1 to n where n is length of the array, sort it in O(n) time complexity.

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
1D array

**Comment by MohammedHassan07** [comment]
@SarthakKeshari 
Kindly assign this issue to me,
I have practiced it on my local machine.

**Comment by SarthakKeshari** [comment]
@MohammedHassan07,
Kindly place your solution in "Sorting" folder.
Deadline - 03/10/2021

**Comment by MohammedHassan07** [comment]
If I make a detailed explanation of the issues I raised  in .txt format, will it acceptable?

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue
