### ISSUE TITLE
Print Binary of number(Bit Manipulation)

### ISSUE THREAD

**Issue by AayushBangroo** [SarthakKeshari/Java-Questions-and-Solutions#62]
### Enter your question - 
Print Binary of a number using Bit Manipulation taking input from user.

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Bit Manipulation, Math

**Comment by AayushBangroo** [comment]
Kindly assign this issue to me.

**Comment by SarthakKeshari** [comment]
@AayushBangroo,
Go ahead, Kindly place your solution in "Bit manipulation" folder.
Deadline - 02/10/2021
