### ISSUE TITLE
Keprekar Number

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/Java-Questions-and-Solutions#65]
### Enter your question - 
Write a program to input a number and check whether it is a Keprekar Number or not.

### Enter link to the question(if question belongs to any online platform) - 
No Link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Mathematical operations and if else statement

**Comment by Vedansh-Keshari** [comment]
@SarthakKeshari 
Kindly assign me this issue and mark it for Hacktoberfest 2021

**Comment by SarthakKeshari** [comment]
@Vedansh-Keshari,
Kindly add you solution to "Number Theory" folder.
Deadline - 02/10/2021
