### ISSUE TITLE
Maximum frequent character in the string

### ISSUE THREAD

**Issue by aadityasinha-dotcom** [SarthakKeshari/Java-Questions-and-Solutions#66]
### Enter your question - 
Given a string str, we need to find maximum occurring character in the string.

### Enter link to the question(if question belongs to any online platform) - 
`N/A`

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Strings

`Example:`

![hacktober2](https://user-images.githubusercontent.com/75474786/135585901-8a9d4e11-cb20-4a81-a019-92da185497f6.PNG)

As a part of Hacktoberfest, @SarthakKeshari please assign this issue to me

**Comment by SarthakKeshari** [comment]
@aadityasinha-dotcom,
Kindly add your question to "String Handling" folder
Deadline - 02/10/2021

Gentle advice for futher Issues -
A bit more tough questions would be appreciated for Hacktoberfest tag.
