### ISSUE TITLE
Chef in Vaccination Queue

### ISSUE THREAD

**Issue by manvikri22** [SarthakKeshari/Java-Questions-and-Solutions#67]
### Enter your question - 
There are N people in the vaccination queue, Chef is standing on the Pth position from the front of the queue. It takes X minutes to vaccinate a child and Y minutes to vaccinate an elderly person. Assume Chef is an elderly person.

You are given a binary array A1,A2,…,AN of length N, where Ai=1 denotes there is an elderly person standing on the ith position of the queue, Ai=0 denotes there is a child standing on the ith position of the queue. You are also given the three integers P,X,Y. Find the number of minutes after which Chef's vaccination will be completed.

### Enter link to the question(if question belongs to any online platform) - 
https://www.codechef.com/START13C/problems/VACCINQ

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array , Basic, Java

**Comment by SarthakKeshari** [comment]
@manvikri22,
Kindly place your solution in "codechef" folder.
Deadline - 02/10/2021

Gentle advice for futher Issues -
Medium and hard level questions will be given preference for Hacktoberfest tag.
