### ISSUE TITLE
Modular Exponentiation (Number Theory)

### ISSUE THREAD

**Issue by AayushBangroo** [SarthakKeshari/Java-Questions-and-Solutions#68]
### Enter your question - 
Given three number 'a' , 'b' and 'm' calculate a^b under modulo 'm'

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Number Theory

**Comment by SarthakKeshari** [comment]
@AayushBangroo,
Go ahead, Kindly add your solution to "Number Theory" folder.
Deadline - 03/10/2021

The question you have come up with is an essential one. So do provide good insight my providing proper comments in your solution file.

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue
