### ISSUE TITLE
Linear Search

### ISSUE THREAD

**Issue by Krush2311** [SarthakKeshari/Java-Questions-and-Solutions#69]
### Enter your question - 
Performing Linear search of any number entered by user in an Array

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array

**Comment by Krush2311** [comment]
Kindly assign this issue to me. Also could you add the label "hacktoberfest"

**Comment by SarthakKeshari** [comment]
@Krush2311,
Kindly place your solution in "Searching" folder.
Deadline - 02/10/2021

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue
