### ISSUE TITLE
less or greater than 10

### ISSUE THREAD

**Issue by Minal2103** [SarthakKeshari/Java-Questions-and-Solutions#7]
### Enter your question - 
write a program to check if number is greater than or less than 10

### Enter link to the question(if question belongs to any online platform) - 
no link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Basic , if

**Comment by Minal2103** [comment]
Kindly assign this issue to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@Minal2103,
Deadline for the task is 25/09/2021.

**Comment by SarthakKeshari** [comment]
Kindly create another issue Add a solution to solve it @Minal2103

**Comment by Krush2311** [comment]
Hello sir, kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@Krush2311,
Kindly add your solution to "Basic Codes" folder.
Deadline - 30/09/2021
