### ISSUE TITLE
binary search in an infinite sorted array

### ISSUE THREAD

**Issue by vish-han** [SarthakKeshari/Java-Questions-and-Solutions#71]
### Enter your question - 
You are given an sorted array, you have to search for element in the array by applying binary search.

### Enter link to the question(if question belongs to any online platform) - 
https://www.geeksforgeeks.org/find-position-element-sorted-array-infinite-numbers/
### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array ,JAVA

**Comment by vish-han** [comment]
Can I work in this issue for the hacktoberfest2021, I will be highly motivated if u assign me to do this task..

**Comment by SarthakKeshari** [comment]
@vish-han,
Kindly place your solution in "GeeksForGeeks" folder if folder is not present then create it.
Deadline - 02/10/2021

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue

**Comment by vish-han** [comment]
Bro no offense to you,  but I can handle this issue and I know some coding too😉
