### ISSUE TITLE
Reorder List

### ISSUE THREAD

**Issue by Ankurrsingh** [SarthakKeshari/Java-Questions-and-Solutions#73]
### Enter your question - 
Reorder List
You are given the head of a singly linked-list. The list can be represented as:

L0 → L1 → … → Ln - 1 → Ln
Reorder the list to be on the following form:

L0 → Ln → L1 → Ln - 1 → L2 → Ln - 2 → …
You may not modify the values in the list's nodes. Only nodes themselves may be changed

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/reorder-list/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Recursion ,linked list

**Comment by SarthakKeshari** [comment]
@Ankurrsingh,
Kindly write whole question description in enter your question section

**Comment by Ankurrsingh** [comment]
> @Ankurrsingh, Kindly write whole question description in enter your question section

check i added whole question

**Comment by SarthakKeshari** [comment]
@Ankurrsingh,
Kindly add your solution to "leetcode" folder.
Deadline - 03/10/2021

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue

**Comment by SarthakKeshari** [comment]
@Ankurrsingh,
Deadline crossed.

**Comment by Anova07** [comment]
@SarthakKeshari kindly assign this task to me

**Comment by aakashjain294** [comment]
please assign this issue to me, I am very proficient in the java language you can check my DsAlgo repository

**Comment by SarthakKeshari** [comment]
@Anova07 
Kindly add your solution to "leetcode" folder.
Deadline - 05/10/2021
