### ISSUE TITLE
Min Max of an Array using Recursion

### ISSUE THREAD

**Issue by devesh-2002** [SarthakKeshari/Java-Questions-and-Solutions#74]
### Enter your question - 
Find Minimum and Maximum of an array using recursion. 

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Recursion, Array
Eg : 
![image](https://user-images.githubusercontent.com/79015420/135595557-97f15350-9ef0-42fb-93e0-b9b0ec5bf4e7.png)
Please assign me this issue, as a part of Hacktoberfest.

**Comment by SarthakKeshari** [comment]
@devesh-2002,
Kindly add your solution to "Recursion" folder.
Deadline - 03/10/2021

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue
