### ISSUE TITLE
Rotate Array

### ISSUE THREAD

**Issue by nik132-eng** [SarthakKeshari/Java-Questions-and-Solutions#76]
### Enter your question - 
Given an array, rotate the array to the right by k steps, where k is non-negative.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/rotate-array/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
ARRAY, JAVA

please assign me this issue for hacktoberfest @SarthakKeshari sir #

**Comment by SarthakKeshari** [comment]
@nik132-eng,
Go ahead, kindly add your solution to "leetcode" folder.
Deadline - 02/10/2021

**Comment by nik132-eng** [comment]
sir code submitted please check it out

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue

**Comment by SarthakKeshari** [comment]
@nik132-eng,
https://t.me/joinchat/7MGxwePEB55iMTk9 - Join this
