### ISSUE TITLE
Javelin Qualification

### ISSUE THREAD

**Issue by aadityasinha-dotcom** [SarthakKeshari/Java-Questions-and-Solutions#77]
### Enter your question - 
There are N players with IDs from 1 to N, who are participating in the Javelin throw competition which has two rounds. The first is the qualification round, followed by the final round. The qualification round has gotten over, and you are given the longest distance that each of the N players has thrown as A1,A2,…,AN. Now, the selection process for the final round happens in the following two steps:

1) If the longest throw of a player in the qualification round is greater than or equal to the qualification mark of M cm, they qualify for the final round.

2) If after step 1, less than X players have qualified for the finals, the remaining spots are filled by players who have thrown the maximum distance among the players who have not qualified yet.

You are given the best throws of the N players in the qualification round A1,A2,…,AN and the integers M and X. Print the list of the players who will qualify for the finals in increasing order of their IDs.

### Enter link to the question(if question belongs to any online platform) - 
https://www.codechef.com/START8C/problems/JAVELIN

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Arrays, HashMaps

As a part of Hacktoberfest, @SarthakKeshari please assign this issue to me

**Comment by SarthakKeshari** [comment]
@aadityasinha-dotcom,
Kindly add your solution to "codechef" folder.
Deadline - 03/10/2021
