### ISSUE TITLE
Emirp Number

### ISSUE THREAD

**Issue by Vedansh-Keshari** [SarthakKeshari/Java-Questions-and-Solutions#78]
### Enter your question - 
Write a program to input a number a check whether it is an Emirp Number or not.

### Enter link to the question(if question belongs to any online platform) - 
No link

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Looping statements and if else statements

@SarthakKeshari 
Kindly assign me the issue,
as a part of Hacktoberfest.

**Comment by SarthakKeshari** [comment]
@Vedansh-Keshari,
Kindly add your solution to "Number Theory" folder.
Deadline - 03/10/2021

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue
