### ISSUE TITLE
Find the Duplicate Number

### ISSUE THREAD

**Issue by SarveshLimaye** [SarthakKeshari/Java-Questions-and-Solutions#79]
### Enter your question - 
Given an array of integers nums containing n + 1 integers where each integer is in the range [1, n] inclusive. There is only one repeated number in nums, return this repeated number.

### Enter link to the question(if question belongs to any online platform) - 
https://leetcode.com/problems/find-the-duplicate-number/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array,cyclic sort

@SarthakKeshari  Pls assign me this issue under hacktoberfest.

**Comment by SarthakKeshari** [comment]
@SarveshLimaye,
Kindly add your solution to "leetcode" folder
Deadline - 03/10/2021
