### ISSUE TITLE
Solution - less than greater than 10

### ISSUE THREAD

**Issue by Minal2103** [SarthakKeshari/Java-Questions-and-Solutions#8]
### Enter Issue id being referred to - 
#7 

### Approach/Algorithm/Pseudo Code for the selected question - 
i will use if for this question 

### Tags for the solution(eg - Array, Basic, Stack, etc.) - 
Basic

**Comment by SarthakKeshari** [comment]
@Minal2103 ,
Deadline will be 25/09/2021

**Comment by SarthakKeshari** [comment]
Kindly place your solution in Basic Codes folder
