### ISSUE TITLE
Check if number is odd or even (Bit Manipulation)

### ISSUE THREAD

**Issue by AayushBangroo** [SarthakKeshari/Java-Questions-and-Solutions#87]
### Enter your question - 
Check if number is odd or Even using Bit Manipulation

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Bit Manipulation

**Comment by shrushti2001** [comment]
assign this to me

**Comment by SarthakKeshari** [comment]
@AayushBangroo, 
Kindly claim your question just after creating as per CONTRIBUTING.md guidlines

**Comment by SarthakKeshari** [comment]
@shrushti2001,
Kindly add your solution to "Bit Manipulation" folder.
Deadline - 02/10/2021

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue

**Comment by SarthakKeshari** [comment]
@shrushti2001,
Deadline crossed

**Comment by AayushBangroo** [comment]
Please assign this to me @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@AayushBangroo,
Kindly add your solution to "Bit Manipulation" folder.
Deadline - 04/10/2021
