### ISSUE TITLE
Counting number of lines, words, characters and paragraphs in a text file 

### ISSUE THREAD

**Issue by dineshparekh11** [SarthakKeshari/Java-Questions-and-Solutions#90]
### Enter your question - 
Counting number of lines, words, characters and paragraphs in a text file using Java

### Enter link to the question(if question belongs to any online platform) - 
https://www.geeksforgeeks.org/counting-number-lines-words-characters-paragraphs-text-file-using-java/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Basic, Stack
![find1](https://user-images.githubusercontent.com/78658348/135617432-c1e95cea-c77f-423b-a1fa-87fcea8ebb15.png)

**Comment by dineshparekh11** [comment]
Kindly assign #90 issue to me

**Comment by SarthakKeshari** [comment]
@dineshparekh11,
Kindly add your solution to "GeeksForGeeks" folder.
Deadline - 03/10/2021

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue
