### ISSUE TITLE
Zigzag traversal of Matrix

### ISSUE THREAD

**Issue by Ln11211** [SarthakKeshari/Java-Questions-and-Solutions#92]
### Enter your question - 
Given a 2D matrix, print all elements of the given matrix in diagonal order. 
For example, consider the following 5 X 4 input matrix.  
Example:

1     2     3     4
5     6     7     8
9    10   11   12
13  14   15   16
17  18   19   20

Diagonal printing of the above matrix is

1
5 2
9 6 3
13 10 7 4
17 14 11 8
18 15 12
19 16
20

### Enter link to the question(if question belongs to any online platform) - 
https://www.geeksforgeeks.org/zigzag-or-diagonal-traversal-of-matrix/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, 2D Array

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue

**Comment by Ln11211** [comment]
@SarthakKeshari sir, done .. can you please review it sir ?
