### ISSUE TITLE
Check if Nth bit is set in a number (Bit Manipulation)

### ISSUE THREAD

**Issue by AayushBangroo** [SarthakKeshari/Java-Questions-and-Solutions#95]
### Enter your question - 
Check if Nth bit is set in a number using Bit Manipulation

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Bit Manipulation

**Comment by AayushBangroo** [comment]
Please assign this issue to me

**Comment by SarthakKeshari** [comment]
@AayushBangroo,
Kindly add your solution to "Bit Manipulation" folder
Deadline - 03/10/2021
