### ISSUE TITLE
Minimum Jumps

### ISSUE THREAD

**Issue by aadityasinha-dotcom** [SarthakKeshari/Java-Questions-and-Solutions#97]
### Enter your question - 
Given an array of integers where each element represents the max number of steps that can be made forward from that element. Return the minimum number of jumps to reach the end of the array. If an element is 0, it cannot move through that element. If the end isn’t reachable, return -1.

### Enter link to the question(if question belongs to any online platform) - 
https://www.geeksforgeeks.org/minimum-number-of-jumps-to-reach-end-of-a-given-array/

### Tags for the question(eg - Array, Basic, Stack, etc.) - 
Array, Basic

`Example:`

![image](https://user-images.githubusercontent.com/75474786/135647519-b4ea33c3-4402-4e5d-9f77-93c23d09e319.png)

As a part of Hacktoberfest, @SarthakKeshari please assign this issue to me

**Comment by SarthakKeshari** [comment]
@aadityasinha-dotcom,
This question belongs to GFG right? Kindly mention the link too.

**Comment by aadityasinha-dotcom** [comment]
> @aadityasinha-dotcom,
> This question belongs to GFG right? Kindly mention the link too.

OKay, I forgot to paste the link.

**Comment by SarthakKeshari** [comment]
@aadityasinha-dotcom,
Kindly save your solution to "GeeksForGeeks" folder
Deadline - 03/10/2021

**Comment by aadityasinha-dotcom** [comment]
> @aadityasinha-dotcom, Kindly save your solution to "GeeksForGeeks" folder Deadline - 03/10/2021

I think there is no GeeksForGeeks folder.
